### ISSUE TITLE
Abfrage mehrerer Organisationen gleichzeitig

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#10]
Um eine Professur und einen Lehrstuhl in einer Publikationsliste zusammenzuführen, müssen zwei OrgaIDs (oder mehr) gleichzeitig abfragbar sein.

Nach Umstellung auf den generischen WS-Zugriff sind dann nur noch kleine Änderungen am WordPress-Code notwendig.

**Comment by cassandre** [comment]
https://github.com/RRZE-Webteam/fau-cris/issues/23
