### ISSUE TITLE
Ausgabe Artikelnummer, wenn keine Seitenzahl vorliegt

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#100]
In der Standardausgabe der Publikationsdatensätze soll die Artikelnummer ausgegeben werden, wenn keine Seitenzahlen eingetragen sind. Beispiel ist Publikation 1066080. Die Artikelnummer ersetzt bei die Seitenzahlen.

Die Information befindet sich im Feld "Article number" des XML-Datensatzes (neu im Export!).

**Comment by cassandre** [comment]
Für welche Publikationstypen ist das relevant? Ich habe es jetzt für Zeitschriftenartikel und Sammelbandbeiträge eingebaut.

**Comment by m-w** [comment]
Reicht aktuell für die beiden.
