### ISSUE TITLE
Auflistung & andere HTML-Notation bei Projektdarstellung

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#101]
(Einige) HTML-Notationen werden bei der Projektdarstellung nicht berücksichtigt (z.B. Aufzählungen):

Bsp: http://cris-demo.zuv.fau.de/cris-custom-demo-aufzaehlungen/

Shortcode: `[cris show=projects project=103397]`

Auch bei [cris-custom] ist die Ausgabe nicht i.O. - bei der Darstellung der Forschungsbereiche funktioniert es bereits (zumindest mit einer Aufzählung).

**Comment by cassandre** [comment]
Die meisten HTML-Tags werden rausgefiltert, um keine Kollisionen mit den Themes zu bekommen. ul, ol und li habe ich jetzt zugelassen. Ggf. Bescheid sagen, wenn noch mehr benötigt wird.
