### ISSUE TITLE
Verlinkung mit WordPress-Kontakt

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#104]
Sind die Kontakte nach dem Schema "Nachname, Vorname (Initial)" angelegt, werden z.B. die Autoren nicht verlinkt. Aktuell funktioniert die Zuordnung nur, wenn die Visitenkarte in der Form "Vorname (Initial) Nachname" angelegt ist.

Auf z.B. der Team-Seite möchte man jedoch nach Nachnamen sortieren, so dass die Kontakte nach dem ersten Schema benannt werden.

Gibt es dafür eine Lösung in WordPress oder muss das Plugin bei der Suche nach den Namen angepasst werden? Gibt es eigentlich vom RRZE eine Vorgabe bei der Anlage von Kontakten?

**Comment by cassandre** [comment]
Im Person-Plugin gibt es separate Felder für Vor- und Nachname, die man automatisch aus UnivIS oder manuell füllen kann. Man könnte bei der DB-Abfrage auch diese Felder mit berücksichtigen. 

Die Schwachstelle bleibt immer, dass der Name weitgehend ähnlich sein muss. Und je mehr Abweichungen man berücksichtigt, desto langsamer die Abfrage.

Die Alternative wäre, zu warten bis es eine Systemübergreifende ID gibt. Oder ein zusätzliches Feld im FAU-Person-Plugin, das die CRIS-ID der Person enthält. Das wäre natürlich aufwändig zu befüllen, v.a. bei größeren Org-Einheiten.

**Comment by xwolfde** [comment]
Als systemübergreifende "Id" ist laut CIO bereits die IdM-Kennung vorgesehen. In UnivIS ist die bereits teilweise drin. 
Das Verfahren mit (meist selbst vergebenen) Initialen zu arbeiten hat bei E-Mail nicht so ganz funktioniert. Dass wäre daher wohl ein Holzweg darauf zu setzen. Ich würde eher darauf warten, dass auch die Kennung als eindeutiges Merkmal genutzt werden kann.

**Comment by m-w** [comment]
Bei der Kennung wird sich kurzfristig nichts tun (siehe https://github.com/RRZE-Webteam/fau-person/issues/194). 

Was bleibt, ist die Herausforderung, auf die verschiedenen Schreibweisen des Namens in den Verwaltungssystemen und der Realität zu reagieren. Die DB-Felder als Option scheinen da eventuell eine schmerzarme Lösung zu sein.

**Comment by cassandre** [comment]
Die Kennungen sind – außer die vom CIO – noch nicht in UnivIS vorhanden. Dann kann man auch nichts entwickeln. Ggf. müsste man da bei den UnivIS-Leuten mal Interesse an diesem Feld bekunden.

Anders als ich dachte, landen die UnivIS-Felder auch nicht in der WP-Tabelle. Das heißt der einzige Weg vom Autor zur Person führt über den "Titel" des Kontakts.

**Comment by m-w** [comment]
Dann brauchen wir doch vorübergehend ein "OR" beim Vergleich mit Vor- und Nachnamen. :-/ Könnte man ggfs. noch eine Option in die Konfiguration einfügen, die das Verhalten konfiguriert? Dann wäre es wenigstens einheitlich innerhalb eines Webauftritts.

**Comment by m-w** [comment]
Bekommen wir Kontakte mit der Bezeichnung `prof-dr-ing-habil-max-mustermann` irgendwie abgebildet?

**Comment by cassandre** [comment]
Mit "LIKE % $firstname % lastname %" ist es relativ Wurscht, was da vorne oder hinten noch an Titeln dranhängt. Dann noch eine Option, in welcher Reihenfolge die Namen im Person-Plugin angelegt werden. Damit müsste man die meisten Fälle eigentlich erschlagen haben.

**Comment by m-w** [comment]
Ich sehe da noch die eine oder andere Nebenwirkung, aber alle Permutationen werden wir eh erst mit einer ID erwischen. Nichts hält länger als ein Provisorium.

**Comment by m-w** [comment]
Bei der Darstellung von Publikationen am Forschungsbereich wird die Einstellung nicht berücksichtigt.

**Comment by m-w** [comment]
Gleiches trifft auf Publikationen auf der Projektdarstellung zu.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/6a9dde910061039cfc66ad11eee9ceac6b132522.
