### ISSUE TITLE
Automatische Ergänzung "weitere Projekte"?

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#105]
Werden Projekte bei der Synchronisation automatisch unter "Weitere Projekte" ergänzt? Ich habe hier eine Meldung, dass dies nicht der Fall ist.

**Comment by cassandre** [comment]
Kann ich leider nicht reproduzieren. 
Eigentlich werden bei jeder Synchronisation die Projekte mit und Forschungsbereich abgeglichen und ggf. ergänzt. Gibt es eine Org-ID zu dem Fall?

**Comment by m-w** [comment]
Das war glaube die 142503 (Testseite unter https://ltm.cms.rrze.uni-erlangen.de/forschung/). Dort scheint es aber im Moment vollständig zu sein.
