### ISSUE TITLE
Wichtige Publikationen einer Person

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#109]
Über das Plug-In sollen die wichtigen Publikationen ausgegeben werden, die Relation ist `PUBL_has_PERS`. 

Ggfs. muss die Liste auch formatier- und sortierbar sein (analog #91 und #82). Standardsortierung ist allerdings die Reihenfolge wie im XML.

**Comment by m-w** [comment]
Shortcode mit `persid=XXX` und `notable=1`

**Comment by cassandre** [comment]
Gibt es eine ID zum testen? Habe meine üblichen Verdächtigen schon ausprobiert und immer size=0 bekommen.

**Comment by m-w** [comment]
Zum Testen: 169100, 1023263, 164161, 163956

**Comment by m-w** [comment]
Hier sollte als Standard auch nur die Liste "wie sie ist" ausgegeben werden (analog #91), aktuell ist das bereits automatisch mit "orderby=date" versehen:

`[cris show=publications persid=169100 notable=1]` vs. `[cris show=publications persid=169100 notable=1 orderby=date]` vs. `[cris show=publications persid=169100 notable=1 orderby=type]`

Die Beschränkung auf eine Anzahl liefert bereits die gewünschte Darstellung: `[cris show=publications persid=169100 notable=1 items=3]`

**Comment by m-w** [comment]
Die Kombination von "items" und "notable" scheint nicht zu funktionieren. Bsp wäre die persID=163617 (eine Publikation von 2017 ist "notable", bei items=3 erscheinen aber drei aus 2017).

**Comment by m-w** [comment]
Eine gegliederte Darstellung von 10 Publikationen ist nicht sinnvoll, wir benötigen also noch ein ein `orderby=none`.

**Comment by cassandre** [comment]
zu https://github.com/RRZE-Webteam/fau-cris/issues/109?_pjax=%23js-repo-pjax-container#issuecomment-329758591: Kann ich nicht reproduzieren. [cris show="publications" persid="163617" notable="1" limit="3"] liefert bei mir die ersten drei Ergebnisse aus [cris show="publications" persid="163617" notable="1"]

**Comment by cassandre** [comment]
zu https://github.com/RRZE-Webteam/fau-cris/issues/109?_pjax=%23js-repo-pjax-container#issuecomment-329759393: standardmäßig wird bei "notable" nicht gegliedert, nur wenn man es explizit so einstellt ([cris show="publications" persid="163617 " notable="1" orderby="type"]).

**Comment by m-w** [comment]
Passt in der dev-Version.
