### ISSUE TITLE
Filterung auf Subtypen analog zu "Weiterer Publikationstyp"

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#112]
Bei Journalbeträgen soll auch auf Subtypen gefiltert werden können, so dass man z.B. Editorials oder Entscheidungsanmerkungen separat ausgeben kann.

Wahrscheinlich sollten wir das gleich bei allen Publikationstypen einführen...

**Comment by cassandre** [comment]
Nützlich wäre dazu eine Liste sämtlicher Subtypen, für das Mapping.

**Comment by m-w** [comment]
Editorial
Erratum
Case study
Letter
Article in Journal
Report
Review article
Short survey
Note
online publication
Entscheidungsanmerkung
undefined

**Comment by cassandre** [comment]
Merci!
