### ISSUE TITLE
Auszeichnungen von Startdatum bis Enddatum

### ISSUE THREAD

**Issue by Tilltheman** [RRZE-Webteam/fau-cris#113]
Bisher gibt es nur die Möglichkeit ab einem Jahr Auszeichnungen anzuzeigen, allerdings gibt es soweit ich das gesehen habe keine Möglichkeit ein Enddatum anzugeben. Wird es so etwas geben, sodass man alle Auszeichnungen von z.B. 1975-2013 selektieren kann?

**Comment by m-w** [comment]
Haben Sie einen Anwendungsfall parat (gerne auch direkt telefonisch oder erstmal an cris-support@fau.de)?

**Comment by m-w** [comment]
Anwendungsfall: Separate Darstellung älterer Preise.

Da ältere Daten in vielen Fällen lückenhaft sind, kann für externe Besucher schnell der Eindruck entstehen, dass der Lehrstuhl in der Vergangenheit weniger leistungsfähig war. Sind die Daten vollständig, so ist ein Enddatum nicht notwendig. 

Daher wird die Funktion aktuell nicht benötigt.
