### ISSUE TITLE
Designunterschied Bereich Forschung / außerhalb

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#115]
Bei Nutzung der Automatik gibt es Darstellungsunterschiede im Menü, welche abhängig von der Seite sind.

Bsp: Startseite (https://www.lap.physik.nat.fau.de/) vs. Forschung (https://www.lap.physik.nat.fau.de/forschung/)

Das Menü auf letzterer enthält den Begriff "Forschungsbereiche" und zusätzliche graue Linien.

**Comment by m-w** [comment]
Wie hoch ist der Aufwand hier einzuschätzen?

**Comment by xwolfde** [comment]
Anmerkung: Ggf. mit der kommenden 1.8er Version des Themes über do_shortcode()  leichter lösbar.
vgl: https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-portalmenu/

**Comment by m-w** [comment]
In der englischen Sprachvariante fehlt die Übersetzung, es bleibt bei "Forschungsbereiche".
