### ISSUE TITLE
Listendarstellung Forschungsbereiche

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#116]
Der Shortcode `[cris show=fields orgid=141496]` liefert bisher nur eine Liste der Namen der Forschungsbereiche. Wenn zu den FBs auf der Website keine eigene Seite existiert, so sollte eine Verlinkung zu CRIS eingefügt werden.

Nebenschauplatz 1: Die Reihenfolge der FBs in der Auflistung ist invertiert.
Nebenschauplatz 2: Das Attribut "orgid" im Shortcode wird ignoriert, es wird immer die Organisation in der Plug-In-Konfiguration genutzt.

**Comment by cassandre** [comment]
Zu Nebenschauplatz2: Bei show=fields kann ich das nicht reproduzieren. Bei show=organisation ist es in https://github.com/RRZE-Webteam/fau-cris/commit/ee5048122e59e0ceed0cffb5015e39314e4e6a1a gefixt.

**Comment by cassandre** [comment]
Hauptissue und Nebenschauplatz 1 erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/f1be49e6fba820dd1b6cf6988f3f420351f5b9d0. Nebenschauplatz 2 nach wie vor nicht reproduzierbar.

**Comment by m-w** [comment]
Passt.
