### ISSUE TITLE
Accordion statt Text als Gliederung

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#117]
Bei langen Publikationslisten ist es sinnvoll, statt die Gliederungsüberschriften als Accordion zu gestalten. Die Zwischenüberschriften sind dann jeweils geschlossen, ggfs. die erste offen.

Als Parameter könnte man `format=....` wählen. Standardeinstellung soll jedoch immer die Darstellung mit normalen Zwischenüberschriften sein.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/74f75f5695eb04211bd389d30776722463d1ba58 und https://github.com/RRZE-Webteam/fau-cris/commit/2191cdc899525165a318c2c19c7ee530f2c5252b.

**Comment by FlorianFiller** [comment]
Frage(n) als Nutzer: 
Was muss ich dann in den Shortcode schreiben, damit es funktioniert? format="accordion" ?
Geht das nur bei Publikationen oder auch bei Drittmittelprojekten etc. aus CRIS?
Funktioniert das auch, wenn ich den Shortcode jetzt schon in Accordions eingebaut habe (bspw.: https://www.phil.fau.de/forschung/publikationen/publikationen-2017/)?

Vielen Dank!

**Comment by cassandre** [comment]
Ja, format="accordion" stimmt. Ist allerdings noch nicht auf den CMS-Instanzen aktualisiert. Sollte aber im Laufe der Woche passieren.
Bislang gibt es das nur bei Publikationen. Für alles andere gerne ein Feature Request ans CRIS-Team.
Accordion in Accordion sollte technisch gesehen funktionieren, würde ich aber von der Benutzerfreundlichkeit her nicht empfehlen. Zwei ineinander verschachtelte Accordions finde ich schon grenzwertig, bei mehr als zwei ist der Besucher ja nur noch am Klicken, bevor er mal eine Information zu lesen bekommt.
