### ISSUE TITLE
Shortcode ignoriert orgid

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#121]
Der Parameter "orgid" wird immer aus den globalen Einstellungen des Plug-Ins überschrieben, anstatt direkt den Wert aus dem Shortcode zu nehmen.

Bsp: `[cris show=organisation orgID=142326]` (wenn z.B. 142319 in den globalen Einstellungen steht).

#116 erwähnt einen vergleichbaren Fehler.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/ee5048122e59e0ceed0cffb5015e39314e4e6a1a.
