### ISSUE TITLE
Export Techreport

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#122]
Beim erzeugen eines Bibtex-Exports eines Techreports sind im Bereich Abstract hml-tags drin (s.u.). 

Zusätzlich ist die Frage, ob man beim Typ statt misc techreport schreiben könnte.

@misc{faucris.1073475,
 abstract = {<span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12.8013px; white-space: pre-wrap;">Many applications in scientific computing require solving one or more partial differential equations (PDEs). For this task, solvers from the class of multigrid methods are known to be amongst the most efficient. An optimal implementation, however, is highly dependent on the specific problem as well as the target hardware. As energy efficiency is a big topic in today&#39;s computing centers, energy-efficient platforms such as ARM-based clusters are actively researched. In this work, we present a domain-specific approach, starting with the problem formulation in a domain-specific language (DSL), down to code generation targeting a variety of systems including embedded architectures. Furthermore, we present an approach to simulate embedded architectures to achieve an optimal hardware/software co-design, i.e., an optimal composition of software and hardware modifications. In this context, we use a virtual environment (OVP) that enables the adaptation of multicore models and their simulation in an efficient way. Our approach shows that execution time prediction for ARM-based platforms is possible and feasible but has to be enhanced with more detailed cache and memory models. We substantiate our claims by providing results for the performance prediction of geometric multigrid solvers generated by the ExaStencils framework. </span>},

**Comment by m-w** [comment]
Die Frage ist hier etwas fehl am Platz, da das WordPress-Plug-In nicht beteiligt ist.

Der HTML-Code ist mit großer Wahrscheinlichkeit durch copy'n'paste entstanden. Abhilfe schafft das Leeren des Abstract-Feldes, "Zwischenspeichern" und neues Einfügen (am besten vorher in einen reinen Texteditor einfügen).

Die Ausgabe als `@techreport` habe ich intern aufgenommen.
