### ISSUE TITLE
Fehler im Plugin für Forschungsbereiche

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#129]
Unter
https://www.phil.fau.de/forschung/fsp/diversitaet-und-globalisierung-in-der-antike/

wird der Beschreibungstext des Forschungsbereiches erst dann oben ausgegeben, wenn auf das dritte Projekt geklickt wird. Die Verlinkung zu CRIS ist hierbei nicht vorhanden.

**Comment by FlorianFiller** [comment]
Das Problem tritt häufiger auf - interessanterweise wohl auch "sprachabhängig":
deutsche Seite: https://www.phil.fau.de/forschung/fsp/bildung-als-transformation/ (problemlos)
englische Seite: https://www.phil.fau.eu/research/fsp/education-as-transformation/ (problematisch)

**Comment by FlorianFiller** [comment]
Ergänzung: es ist nicht immer das dritte Projekt - hier ist es das elfte/letzte:
https://www.phil.fau.eu/research/fsp/middle-ages-and-early-modernity-knowledge-tradition-practices-imagination/

**Comment by cassandre** [comment]
Sind die Texte für den jeweiligen **Forschungsbereich** ursprünglich per Copy/Paste von der Phil-Website ins CRIS kopiert worden? Und standen die auf der Website in einem Accordion? Es sieht nämlich so aus, als wäre da der Quelltext des Accordions (<div class="accordion-body"...>) mit nach CRIS kopiert worden.

**Comment by BastianMelsheimer** [comment]
Die Forschungsbereiche waren scheinbar tatsächlich so befüllt. Wir haben das jetzt überall rausgenommen und unseren Cache refreshed. Die oben genannten Seiten funktionieren jetzt.

**Comment by cassandre** [comment]
Kann in Zukunft nicht mehr vorkommen: divs werden jetzt auch rausgefiltert. War bei den Projekt-Texten schon so, bei den Forschungsbereichen habe ich es jetzt ergänzt. Ist schon auf den CMS-Instanzen aktiv.

**Comment by m-w** [comment]
Letztlich ist HTML in diesem Feld erlaubt. Grundsätzlich könnte man mit `:not`-Selektor und einigem anderen wackeligem Voodoo das Problem umschiffen. Ich hoffe jedoch, dass der HTML-Editor in der kommenden Softwareversion von Converis/CRIS nicht mehr alles schluckt...
