### ISSUE TITLE
Anführungszeichen im Projekttitel -> Falsche Ausgabe bei Forschungsbereich

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#131]
Enthält ein Projekttitel ein Anführungszeichen ("), so wird in der Auflistung der Projekte bei Ausgabe des Forschungsbereiches / Schwerpunktes statt des Projekttitels nur "Tab" ausgegeben.

**Comment by m-w** [comment]
Sollte man hier nicht gleich `htmlentities` nehmen?
