### ISSUE TITLE
Projekttitel liegt nur in Englisch vor: leere Ausgabe

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#138]
Wenn der Projekttitel nur in English vorliegt und die Spracheinstellung von WordPress in Deutsch ist, wird ein leerer Titel angezeigt. Die Variante "deutscher Titel und englische Website" ist schon berücksichtigt (wenn ich mich nicht irre).

Bsp: https://www.phil.fau.de/forschung/fsp/menschenrechte-migration/ und Projekte ID 104483 bzw. 103161

**Comment by m-w** [comment]
Das gleiche trifft auf den Abstract zu. Sollten wir auch beheben. Bsp ist ID 104642.

**Comment by m-w** [comment]
Bei der Darstellung innerhalb der Synchronisation scheint das Problem mit dem Titel weiterhin aufzutreten:

![image001](https://user-images.githubusercontent.com/2520090/36374361-5e47d8b2-156b-11e8-9bc2-709652229286.png)

"Leider" hat der Lehrstuhl beide Sprachen ergänzt, so dass es online nicht mehr sichtbar ist.

**Comment by cassandre** [comment]
Sollte mit https://github.com/RRZE-Webteam/fau-cris/commit/25dd2a1196c042ced6da47ba1381e1f37543e917 erledigt sein.
