### ISSUE TITLE
Englische Ausgabe

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/fau-cris#14]
Die englische Sprachversion funktioniert derzeit nur, wenn die Spracheinstellung der CMS-Instanz "English (UK)" ist, aber nicht mit "English (United States)". Lässt sich das korrigieren?

Außerdem ist die Frontend-Ausgabe offensichtlich weitgehend nicht übersetzt: Die Zwischenüberschriften bei "Pubtype" bleiben alle in deutsch (also "Zeitschriftenartikel" statt "Articels in Journals" etc.). Nurdie Fehlermeldung "Es wurden keine Publikationen gefunden" erscheint auf Englisch.

**Comment by xwolfde** [comment]
Bei den Themes wird ab morgen die selbe Sprachdatei als Kopie auch für en-GB bereitgestellt.
Bitte abklären, ob und was der Standard des Sprachendienstes ist.
Meiner Erinnerung nach war es  en-US, bin mir aber nicht mehr sicher.

Hallo @dmccosh , können Sie da helfen?

**Comment by dmccosh** [comment]
Hallo Wolfgang,
die Universitätsleitung hat britisches Englisch (en-GB) in der Beschluss von 9.9.2015 festgelegt.
Viele Grüße,
Daniel

Von: Wolfgang Wiese [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. März 2016 13:57
An: RRZE-Webteam/fau-cris
Cc: McCosh, Daniel
Betreff: Re: [RRZE-Webteam/fau-cris] Englische Ausgabe (#14)


Bei den Themes wird ab morgen die selbe Sprachdatei als Kopie auch für en-GB bereitgestellt.
Bitte abklären, ob und was der Standard des Sprachendienstes ist.
Meiner Erinnerung nach war es en-US, bin mir aber nicht mehr sicher.

Hallo @dmccosh<https://github.com/dmccosh> , können Sie da helfen?

**Comment by dmccosh** [comment]
Allerdings ist es en-US an dem Fachbereich Wirtschaftswissenschaften.
Wir könnten die Sprachdatei für en-US anpassen.


Von: Wolfgang Wiese [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. März 2016 13:57
An: RRZE-Webteam/fau-cris
Cc: McCosh, Daniel
Betreff: Re: [RRZE-Webteam/fau-cris] Englische Ausgabe (#14)


Bei den Themes wird ab morgen die selbe Sprachdatei als Kopie auch für en-GB bereitgestellt.
Bitte abklären, ob und was der Standard des Sprachendienstes ist.
Meiner Erinnerung nach war es en-US, bin mir aber nicht mehr sicher.

Hallo @dmccosh<https://github.com/dmccosh> , können Sie da helfen?

**Comment by xwolfde** [comment]
Danke für die Info.... Mist, das ging an uns vorbei.
Wir machen es erstmal von Haus.

**Comment by xwolfde** [comment]
@AstridSemm Bitte obiges beachten und ggf. in Doku unter Hinweise mit aufnehmen?

**Comment by pdees** [comment]
Die Sprachausgaben sind jetzt mit Englisch angeglichen, vielen Dank dafür. Es bleibt aber das Problem, dass das CRIS-Plugin nicht vollständig übersetzt ist, insbesondere die Zwischenüberschriften bei der Ausgabe nach pub-type bleiben Deutsch, ebenso das Title-Attribut des Links zur Publikation ("Detailansicht in neuem Fenster öffnen) und die Kürzel "Hrsg." (statt "Ed.") und "S." (statt "p." bzw. "pp.").

**Comment by xwolfde** [comment]
Randnotiz: CRIS-Support/Weiterentwicklung muss mit CRIS-Projektleitung geklärt werden.

**Comment by cassandre** [comment]
fixed in V1.73
