### ISSUE TITLE
Unerwünschte Linkauszeichnung im Abstract-Text...

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#141]
In der englischen Spracheinstellung (siehe auch #138) liefert folgender Code den Abstract inkl. eines Links am Ende des ersten Absatzes, welcher in den Originaldaten nicht enthalten ist:

`[cris-custom show=projects project=104642]`
`#description#`
`[/cris-custom]`

**Comment by cassandre** [comment]
Kann ich leider nicht reproduzieren. Ich habe mittlerweile noch einen anderen Bug an der Stelle gefunden, vielleicht passt das ja dann.

**Comment by m-w** [comment]
Bei mir auch nicht mehr: https://cris-demo.zuv.fau.de/issue-140-link-da-wo-keiner-ist/ (ohne Code-Änderung im Plug-in).
