### ISSUE TITLE
cris custom für Publikationen

### ISSUE THREAD

**Issue by fkranz** [RRZE-Webteam/fau-cris#147]
Es wäre schön auch für Publikationen die Gestaltungsmöglichkeiten wie für Projekte etc mit dem [cris custom] tag zu haben. Insbesondere um dort auch zB das Projekt anzuzeigen, dem die Publikation zugeordnet ist.

**Comment by cassandre** [comment]
cris-custom für Publikationen ist kein Problem, wird erledigt.
Das Projekt zu einer Publikation darzustellen dürfte datentechnisch allerdings ziemlich aufwändig sein. @m-w könnt ihr da eine Autorelation bauen?

**Comment by m-w** [comment]
Die [Abfrage an sich](https://cris.fau.de/ws-cached/1.0/public/infoobject/getrelated/Publication/111061544/PROJ_has_PUBL) ist kein Problem.

Wenn man das nicht standardmäßig bei allen Publikationen macht, sondern nur, wenn es gewünscht ist, sollten die Abfragen auch nicht explodieren. Oder sollten wir ein Spiegelattribut bei allen Publikationen befüllen?

**Comment by cassandre** [comment]
Wäre ein Spiegelattribut aufwändig? Ich würde es sowieso nur in cris-custom anbieten, oder denkst du, da ist eine größere Nachfrage?

**Comment by m-w** [comment]
Wenn es nur bei `cris-custom` verfügbar ist, dann ohne Spiegelattribut. Wenn es eine größere Nachfrage geben sollte, dann stellen wir das um.

**Comment by cassandre** [comment]
Erledigt. Verfügbare Platzhalter sind: 
```
#author#
#title#
#url#
#city#
#publisher#
#year#
#pubType#
#pubStatus#
#pagesTotal#
#pagesRange#
#lexiconColumn#
#volume#
#series#
#seriesNumber#
#ISBN#
#ISSN#
#DOI#
#URI#
#editors#
#bookTitle#
#journalTitle#
#eventTitle#
#eventLocation#
#eventStart#
#eventEnd#
#originalTitle#
#language#
#bibtexLink#
#subtype#
#articleNumber#
```

**Comment by m-w** [comment]
Bitte noch in die [Dokumentation](https://www.wordpress.rrze.fau.de/plugins/fau-cris/erweiterte-optionen/) aufnehmen.

**Comment by cassandre** [comment]
Erledigt.
