### ISSUE TITLE
Sortierung Projekte/Publikationen zu Forschungsbereichen

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#148]
Die Sortierung von Projekten innerhalb eines Forschungsbereiches wird nicht (mehr) korrekt dargestellt.

`[collapse title="Projekte zu diesem Forschungsbereich" color="techfak"]`
`[cris-custom show=fields field=40]`
`#projects#`
`[/cris-custom]`
`[/collapse]`

Hier sollte "SFB/TRR 103 (B02)" zuerst und "EXC15 EAM (E2)" ist Nummer 2.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/8d637d0e5fccea4e443953e6f31d7cd5c57748cd. 
Zahlen als String sortieren ergibt halt 1, 11, 12, 13...

**Comment by m-w** [comment]
Davon sind auch die Publikationen zum Forschungsbereich betroffen (z.B. [CRIS](https://cris.fau.de/converis/portal/project/126522200?lang=de_DE) vs. [Homepage](https://www.wtm.tf.fau.de/forschung/hochtemperaturwerkstoffe/prozesstechnik/einkristalline-erstarrung-mit-verbesserter-mikrostruktur/)).

**Comment by cassandre** [comment]
Die Reihenfolge in der Relation Right Seq entspricht allerdings nur ungefähr der Reihenfolge auf der CRIS-Seite (https://cris.fau.de/ws-cached/1.0/public/infoobject/getrelated/Project/126522200/proj_has_publ vs. https://cris.fau.de/converis/portal/project/126522200?lang=de_DE)

**Comment by m-w** [comment]
Im Forschungsportal wird mangels Alternative nach dem Publikationsjahr sortiert (frag' lieber nicht). "Echt" sieht das so aus:

![publist](https://user-images.githubusercontent.com/2520090/41853920-44f0ed0e-788f-11e8-8e26-65ed7ceb3f1b.png)
