### ISSUE TITLE
Filter auf Sprache der Publikation

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#150]
Publikationslisten sollten nach Sprache filterbar sein, á la 

`[cris show="publications" persID="XX" type="zeitschriftenartikel" language="german"]`

Eine einheitliche Nomenklatur ist dafür allerdings zuvor notwendig. Das Attribut selbst ist unter `Language` bereits im Webservice vorhanden (Beispiel wäre die Publikation 107714684).

**Comment by cassandre** [comment]
Ich würde einfach die vorgeschlagene Liste im CRIS-Backend auf englisch und kleingeschrieben nehmen. Muss man natürlich auf wordpress.rrze.fau.de entsprechend dokumentieren.

**Comment by m-w** [comment]
Die Liste wäre aktuell diese:

<pre>
German
English
Arabic
Chinese
Danish
Finnish
French
Greek
Italian
Japanese
Latin
Dutch
Norwegian
Polish
Portuguese
Russian
Swedish
Slovak
Slovenian
Spanish
Czech
Turkish
Ukrainian
</pre>

Ich kann mir vorstellen, dass es hier Erweiterungen geben wird, wenn das Feature umgesetzt ist. Aber das werden wir ja sehen.

**Comment by cassandre** [comment]
Erledigt: https://github.com/RRZE-Webteam/fau-cris/commit/caa38fe8044f8e959fcf7cf3fd9565786c1792bd.
