### ISSUE TITLE
CRIS liefert FATAL Error bei falschen Ids.

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-cris#152]
Ein Kunde hat in seiner Einstellung im Backend die ID
"143044,142505"
gehabt.
Die Nummer 143044 war wohl falsch.
Dies hatte leider den Effekt, daß WordPress beim Ausführen des Shortcodes abgebrochen ist. Sowas sollte niemals passieren, auch wenn die Nummer inkorrekt ist. Dann sollte eine Fehlermeldung kommen, aber kein  FATAL geworfen werden.

Bitte prüfen und beheben.

**Comment by cassandre** [comment]
Lag nicht an falscher ID (das wird entsprechend abgefangen), sondern an vom Webservice falsch gelieferten Daten. Wurde behoben.
