### ISSUE TITLE
Projektende ausblenden

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#153]
Bei "Projekten aus Eigenmitteln" ist oftmals das Enddaum unklar. Damit werden teilweise Daten in ferner Zukunft eingegeben, die man aber nicht auf der Homepage sehen will.

Hierzu sollte die bestehende `hide`-Option erweitert werden um `project_enddate`.

**Comment by BNeuner** [comment]
Falls kein Projektende in CRIS spezifiziert ist (dort kein verpflichtendes Feld), wird sogar einfach der 31.12.00 als Datum gesetzt/angezeigt.

**Comment by m-w** [comment]
Bei fehlender Angabe liegt das Projektende automatisch drei Jahre nach Projektstart. Das mag nicht überall passen, ist aber mit Blick auf die allgemeine Datenlage an der Uni absolut notwendig.

**Comment by BNeuner** [comment]
12/31/00 wird aber unabhängig vom Projektstart gesetzt und nicht automatisch drei Jahre nach Projektstart? 

In jedem Fall löst die hide-Option das Problem.

**Comment by m-w** [comment]
Ein festes Datum gibt es eigentlich nicht, kann ich vielleicht IDs für Beispieldatensätze haben (gerne alternativ auch per Mail an cris-support@fau.de)?

**Comment by m-w** [comment]
Lösung: Dem Datensatz in CRIS wurde ein falsches Enddatum zugewiesen. Das ist jetzt korrigiert, somit verbleibt die ursprüngliche Aufgabe zum `hide`.

**Comment by m-w** [comment]
Ggfs. wäre auch eine generische Erweiterung á la `hide=project.enddate,publication.bibtex` denkbar.

**Comment by cassandre** [comment]
Sollte mit https://github.com/RRZE-Webteam/fau-cris/commit/ce6825a3501220794944d1e09154ce3c0510f5fb erledigt sein. 

Das Attribut "hide" nimmt eh mehrere, mit Komma getrennte Elemente entgegen: `hide="details, abstract, publications, end"` gibt es momentan. Ist das das, was du im letzten Kommentar meintest?

**Comment by m-w** [comment]
Nicht ganz. Jetzt ist es z.B. noch nicht möglich, den DOI in einer Publikationsliste und das Enddatum von Projekten bei der Anzeige eines Forschungsbereiches auszublenden. Das ist aber eher etwas für später.

**Comment by cassandre** [comment]
OK. Dann bräuchte ich aber eine Liste aller Elemente, die ausblendbar sein sollen. Oder sollen grundsätzlich alle Elemente einzeln ausblendbar sein, inkl. durchreichen zur Unterliste?

**Comment by m-w** [comment]
Ursprungsthema gelöst, Rest wie hinterlegt generisch.
