### ISSUE TITLE
IDM-Kennung bei Personenbezug

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#155]
Der Webservice unterstützt anstatt der numerischen ID nun auch die IDM-Kennung von Personen. Wäre also ganz praktisch, wenn das Plug-In das auch unterstützt (derzeit nicht, wohl nur numerische Inhalte).

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/fau-cris/commit/a9d174d3c531001b2cbb8a5fa203a78391e534d8 erledigt.
