### ISSUE TITLE
FAU.ORG Nummer bei Organisationsbezug

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#156]
Der Webservice unterstützt anstatt der CRIS-internen ID nun auch die FAU.ORG Nummer für Organisationen. Wahrscheinlich funktioniert das bereits jetzt - da auch numerisch - aber ein Test schadet sicher nicht. Anschließend muss die [Dokumentation](https://www.wordpress.rrze.fau.de/plugins/fau-cris/) angepasst werden.

**Comment by cassandre** [comment]
Funktioniert. Doku erledigt.
