### ISSUE TITLE
Unklares Verhalten bei Beschränkung der Anzahl via "items"

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#158]
Nutzt man die Option "items", so scheint die Auswahl der "ersten" nicht in jedem Fall nachvollziehbar zu sein.

Beispiel:

`[cris show="publications" persID="163956" type="zeitschriftenartikel" items="5"]`
`[cris show="publications" persID="163956" type="zeitschriftenartikel"]`

Die per "items" ausgegebenen Datensätze sind nicht die ersten fünf der kompletten Liste.

**Comment by cassandre** [comment]
Die Publikationen, die in den beiden Listen nicht übereinstimmen, haben alle das selbe virtualdate (2018-01-01). Es ist also keine der beiden Sortierungen wirklich falsch.
Ich versuche aber mal herauszukriegen, warum jeweils unterschiedlich sortiert wird, denn verwirrend ist es schon.

**Comment by cassandre** [comment]
Keine Ahnung mehr, in welchem Commit das dabei war, aber mittlerweile funktioniert's.
