### ISSUE TITLE
Ausgabe von Kontaktpersonen der Forschungsbereiche

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/fau-cris#159]
Gibt es einen Shortcode, um die FAU Kontaktperson(en) der Forschungsbereiche auf den Webseiten mit auszugeben?

**Comment by cassandre** [comment]
@mduven: Momentan nicht, ist aber sicher sinnvoll.
@m-w: Könntest du mir dafür noch die CRIS-ID der Kontaktpersonen mit in den Webservice werfen? Dann kann ich auch gleich wieder schicke Links bauen.

**Comment by m-w** [comment]
Hm, geht das nicht [schon](https://www.lap.physik.nat.fau.de/forschung-weber/elektronentransport-auf-molekularer-skala/)?

**Comment by cassandre** [comment]
Auf http://www.test.rrze.uni-erlangen.de:2175/cris/cris-forschungsbereich/ habe ich es mal umgesetzt. Links zu lokalen Personenseiten werden natürlich gesetzt. Aber wenn statt dessen zur CRIS-Personenseite verlinkt werden soll (kann man in den Optionen einstellen), brauche ich die CRIS-ID.

**Comment by m-w** [comment]
Leider unterstützen wir noch keinen Aufruf im Forschungsportal via IDM-Key, der würde ja schon enthalten sein (`contact`).

**Comment by m-w** [comment]
Die IDs stehen jetzt im Feld `contact_ids` (komma-getrennt). Was im Cache ist, braucht ein Seeding für die Auslieferung.
