### ISSUE TITLE
cris-custom Forschungsbereiche

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/fau-cris#160]
Lassen uns z.B. auf der Seite https://www.tm.rw.fau.de/forschung/forschungsschwerpunkte/constraint-based-innovation/ einige Elemente ausgeben:

[cris-custom show=fields field=203331441]
#title#
#description#
Publikationen
#publications#
[/cris-custom]

Habe dazu 2 Fragen:
Wonach werden die Publikationen denn sortiert? Sieht nämlich anders aus als auf https://cris.fau.de/converis/portal/Forschungsbereich/203331441?auxfun=&lang=de_DE

Gibt es eine Möglichkeit, Einfluss auf die Anzahl der angezigten Publikationen zu nehmen?

**Comment by cassandre** [comment]
Die Publikationen werden in der Reihenfolge angezeigt, in der sie in CRIS dem Forschungsbereich zugeordnet sind. Standardmäßig werden nur die ersten 5 angezeigt – eigentlich sollen beim Forschungbereich nur herausragende Publikationen genannt werden. 

Es gibt zwei Möglichkeiten, das zu ändern:

- publications_limit="20" erhöht die Anzahl entsprechend, publications_limit="-1" liefert alle. Die Reihenfolge bleibt jedoch wie oben beschrieben.
- publications_orderby="year" liefert eine nach Jahren abwärts gegliederte List (wie sonst bei Publikationenen auch). Hier werden immer alle Publikationen ausgegeben.
