### ISSUE TITLE
Erweiterung "current" bei Projekten

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#161]
Aktuell kann man per `current=1` aktuell laufende Projekte abfragen. Dies soll um

`0` = abgelaufene Projekte
`2` = laufende und zukünftige Projekte
`3` = zukünftige Projekte

erweitert werden.

**Comment by cassandre** [comment]
Gibt es einen Bedarf für laufend und abgeschlossen? Fehlt in der Liste noch. Und eigentlich steht "1" für true... Hmm, mal schauen, wie man das am elegantesten löst.

**Comment by m-w** [comment]
Für "laufend und abgeschlossen" haben wir noch keine Bedarfsmeldung, schadet aber nicht.

Sicherlich ist `current` für die Fälle unpassend benannt, ich habe nichts gegen einen weiteren Parameter, bei dem `current=1` ein Subset ist. Wenn wir das machen, dann kann man auch gleich sprechende Attributswerte einführen.

Im Code erfolgt aktuell ein Vergleich auf `current='1'`, das wäre kein Hindernis (ändert aber nichts an der unpassenden Bezeichnung).

**Comment by cassandre** [comment]
Wie wäre es mit `status="completed|current|future"` ?
