### ISSUE TITLE
Accordion Formatierung funktioniert nicht für Projekte

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#162]
Für Publikationen ist der Shortcode 

`format="accordion"`

 möglich. Dieser soll auch für Projekte verfügbar gemacht werden.

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/fau-cris/commit/2665437b31a09a11e025d602c9eb05d7b3972ec3 erledigt. Sinnvollerweise für alle anderen Listen (Auszeichnungen, Aktivitäten und Patente) gleich mit
