### ISSUE TITLE
Forschungsbereich mit mehreren Lehrstühlen verknüpft...

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#167]
Kommt das Plug-In mit dem Fall zurecht, wenn sich mehrere Organisationseinheiten einen Forschungsbereich teilen?

**Comment by cassandre** [comment]
Ich wüsste nicht, warum nicht. `getrelated/Organisation/.../fobe_has_orga` geht ja von der Organisation aus. Ob da noch andere Organisationen am Forschungsbereich hängen, dürfte da nichts ausmachen. 
Schick einfach mal eine Orga-ID, bei der das der Fall ist, dann kann ich testen.

**Comment by m-w** [comment]
Wir haben seit einiger Zeit Beispiele live, wie 142677834. Wenn es nach Tests keine Auffälligkeiten gibt, bitte Ticket schließen.

**Comment by m-w** [comment]
Nichts gehört, also gut.
