### ISSUE TITLE
Unerwünschtes Inline-CSS

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-cris#171]
Auf www.fau.de wird auf der Startseite, wo keine CRIS-Information dargestellt wird, dennoch dieses CSS im Kopf eingefügt:

```html
<style type="text/css">
 #nav .level2 li.cris-last {
 border-bottom: 1px solid #aaa;
 padding-bottom: 10px;
 margin-bottom: 10px;
 }
 
 #nav .level2 li.cris-first {
 border-top: 1px solid #aaa;
 padding-top: 10px;
 }
  
 #nav .level2 li.cris-first:before {
 content: 'Forschungsbereiche';
 display:block;
 color: #fff;
 font-weight: bold;
 margin-bottom: 5px;
 }
 #nav .level2 li.cris-last a {
 border-bottom-color: transparent;
 }
 </style>
```

Bitte wegmachen! Plugin CSS und JS darf nur geladen werden, wenn es gebraucht wird.
(Und wenn gehört sowas auch in einer CSS-Datei.)

**Comment by cassandre** [comment]
Wurde in FAU-Einrichtungen übernommen: 
https://github.com/RRZE-Webteam/FAU-Einrichtungen/commit/e646f61e9e96bd3438932613e99ae949ad6a4e44
