### ISSUE TITLE
Cris Custom für Projekte gibt leere Felder aus

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#177]
Beispiel:

https://www.lap.physik.nat.fau.de/forschung-weber/graphen/wechselwirkungseffekte-in-und-gateloses-strukturieren-von-epitaktischem-graphen-auf-siliziumkarbid-0001/

Hier sollten bei den leeren Feldern die Überschriften ausgeblendet werden.

**Comment by m-w** [comment]
Betrifft also die automatische Synchronisierung.

**Comment by cassandre** [comment]
Ich habe mal nachgeschaut: Das geht leider nicht so einfach. Die Beschriftung wird von Hand vor das Feld geschrieben. D.h. da steht dann z.B. `Akronym: #acronym#`. Dadurch kann jeder entscheiden, ob die Beschriftung angezeigt und wie sie formatiert werden soll.

Der Inhalt wird dann tatsächlich (natürlich) nicht ausgeliefert, wenn das Feld leer ist, aber die Beschriftung bleibt wie ganz normaler Text stehen.

Beim Synchronisieren wird auch nicht jedes Projekt nach vorhandenen Feldern geparst – das würde zu lange dauern, da dann ja auch Autorelationen zu Personen und Publikationen durchsucht werden müssten.

Theoretisch könnte man die Platzhalter im Custom-Shortcode so umarbeiten, dass eine mögliche Beschriftung mit angegeben werden kann. Z.B. `#members|Projektbeteiligte: #`. Macht aber natürlich wesentlich mehr Aufwand beim rendern: Da müsste ich mich erst mal ein paar Wochen mit RegEx anfreunden, währen die momentane Lösung sehr pflegeleicht mit strtr() funktioniert.

Es ist ohnehin nur ein Problem bei Sync, d.h. es betrifft nicht viele Nutzer. Und auf den betroffenen Seiten kann man die leeren Zeilen ja von Hand rauslöschen, das wird nicht überschrieben. Da wären meines Erachtens die anderen Issues wichtiger. Ein Bug ist es jedenfalls nicht.

**Comment by m-w** [comment]
Könnte man den "Fix" irgendwo sinnvoll dokumentieren?

**Comment by cassandre** [comment]
Im letzten Drittel von https://www.wordpress.rrze.fau.de/plugins/fau-cris/automatische-synchronisierung/ wird das ja implizit angesprochen: Sync auch mit cris-custom möglich; Synchronisierung löscht keine Daten. Da kann man das noch gut vor den hervorgehobenen Absatz schreiben.

**Comment by m-w** [comment]
Ich meinte eher direkt folgenden Satz: 

> Und auf den betroffenen Seiten kann man die leeren Zeilen ja von Hand rauslöschen, das wird nicht überschrieben.

Darauf kommen die einige/viele Anwender nicht von selbst.

**Comment by cassandre** [comment]
Ja, genau den Satz an die beschriebene Stelle, meinte ich.

**Comment by cassandre** [comment]
Done.

**Comment by m-w** [comment]
Könnte das vielleicht auch mit einem deutlichen Signal dargestellt werden? Ggfs. mit einer Einführung wie: "Einmalige Anpassung ggfs. notwendig: Enthält ein Datensatz keine Informationen zu einem bestimmten Attribut (z.B. Akronym), so müssen Sie nach der Seitenerstellung das entsprechende Tag entfernen".

Oder reden wir hier noch irgendwie aneinander vorbei?
