### ISSUE TITLE
Aktivitäten: Leerstring nicht anzeigen

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#178]
Wenn bei der Aktivität "Gutachtertätigkeit für eine Förderorganisation" keine weitere Beschreibung angegeben wird, sollte kein "Leerstring" ausgegeben werden.

Siehe [Beispiel](https://www.germanistik.phil.fau.de/person/habermann-mechthild/), Aktivitäten, Gutachten.

**Comment by cassandre** [comment]
Ist schon in https://github.com/RRZE-Webteam/fau-cris/commit/5f6945737aabee4709f6d24d289281fec17090d5 gefixt. Kommt dann mit dem nächsten Update.
