### ISSUE TITLE
Aktivitäten: Ausblenden der Typangabe

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#179]
Gruppiert man Aktivitäten nach deren Typ, ist die Ausgabe des Typs bei jeder Zeile unnötig.

Siehe [Beispiel](https://www.germanistik.phil.fau.de/person/habermann-mechthild/), Aktivitäten & Unterpunkte. Hier ist die mehrfache Ausgabe von z.B. "FAU-interne Gremienmitgliedschaft / Funktion" unschön.

Kann man dazu ein Flag einbauen?

**Comment by cassandre** [comment]
Bei nach Typ gruppierten Listen wird der Typ bereits ausgeblendet (analog bei den Jahren). Im Beispiel oben werden einzelne gefilterte Abfragen verwendet: `[cris show="activities" persID="..." type="herausgeberschaft"]`. Da man aber auch nach mehreren Typen filtern kann, kann die Anzeige des Typs schon sinnvoll sein.

Vorschlag: Attribut `hide="type"`. Außerdem noch die automatisierte Darstellung als Accordion (`format="accordion"`), wie es bereits für die Publikationen verfügbar ist (was das obige Beispiel auf eine statt sieben einzelne Abfragen reduzieren würde).
