### ISSUE TITLE
Neuer Subtyp für Herausgeberschaft

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#186]
Bei der Herausgeberschaft gibt es einen neuen Subtype mit der Kennung "specialissue". Auf Deutsch wäre das "Themenheft einer Zeitschrift" und auf Englisch "Special issue of a journal".

**Comment by cassandre** [comment]
Gibts da auch 'ne ID zum testen? Das CRIS Webfrontend eignet sich ja leider nicht so wirklich für eine detaillierte Suche.

**Comment by m-w** [comment]
215864784 sollte passen.
