### ISSUE TITLE
Erweiterung von "notable" auf Forschungsbereiche

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#191]
Der Filter "noteable" soll auf eine besondere Publikationsliste eines Forschungsbereiches anzeigen.

Im Gegensatz zu den wichtigsten Publikationen einer Person ist das nicht nur eine eigene Relation, sondern es kommt noch ein Relationsattribut hinzu ([Beispiel](https://cris.fau.de/ws-cached/1.0/public/infoobject/getrelated/Forschungsbereich/142671642/FOBE_has_cur_PUBL)). Nur wenn `curationsetting` auf `curation_accepted` steht, soll die Publikation angezeigt werden.

**Comment by cassandre** [comment]
Gibt es auch ein Beispiel, bei dem das curationsetting schon gesetzt ist? Oder wird das nur noch nicht an den Webservice weitergegeben?

**Comment by m-w** [comment]
Das Attribut ist teilweise auf Relationen gesetzt beim FoBe Nummer 216449341.

**Comment by cassandre** [comment]
Geht jetzt mit dem Shortcode-Attribut `publications_notable="1"`.
