### ISSUE TITLE
Darstellung Gutachtertätigkeiten, Spezialfall

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#200]
Wenn "Ausländische Drittmittelgeber (keine EU-Mittel)" gewählt ist und eine genauere Angabe vorliegt, muss diese auf den Homepages auch angegeben sein.

Aktuell sieht das so aus:

> Ausländische Drittmittelgeber (keine EU-Mittel)
> (Gutachtertätigkeit für eine Förderorganisation)
> seit 1. Januar 2018

Beispieldaten: 200417965

**Comment by cassandre** [comment]
Meinst du im genannten Fall den "Schweizer Nationalfonds (SNF)"? Den bekomme ich leider nicht aus der Schnittstelle geliefert.

**Comment by m-w** [comment]
Die Information wäre via `getrelated/activity/200417965/ACTI_has_FUND` abfragbar. Das wäre ein zusätzlicher Request, also lieber in `mirror_fund` spiegeln?

**Comment by cassandre** [comment]
Spiegeln bedeutet, du packst es direkt in ein Feld in der Webservice-Abfrage der Aktivität? Dann gerne, ja!

**Comment by m-w** [comment]
Theoretisch müsstest du irgendwo schon das Feld benutzen, oder?

**Comment by cassandre** [comment]
Nein, deshalb wird es ja nicht dargestellt.
Ich verarbeite bislang nur die Infos die ich aus den Abfragen acti_has_orga, acti_has_pers bzw. get/Activity bekomme.

**Comment by cassandre** [comment]
Sorry, doch, das Feld mirror_fund gibt es schon und es wird verwendet. Aktuell steht da im konkreten Fall "Ausländische Drittmittelgeber (keine EU-Mittel)", d.h. da bräuchten wir eine andere Lösung.

**Comment by m-w** [comment]
Ich habe das Relationsattribut analog zu den "anderen Mittelgebern" jetzt dort reinkopiert. Damit entfällt das Ausländische Drittmittelgeber (keine EU-Mittel)" und wird zu "Schweizer Nationalfonds (SNF)".

**Comment by cassandre** [comment]
Passt das so? Dann kann das Ticket geschlossen werden.
<img width="549" alt="Bildschirmfoto 2020-07-14 um 09 47 34" src="https://user-images.githubusercontent.com/4435815/87399071-1d54b880-c5b7-11ea-8eeb-5ef15282890b.png">

**Comment by m-w** [comment]
Ja, das passt so.
