### ISSUE TITLE
Bildquelle wird bei Preisträgern und Akademiemitgliedschaften nicht mehr angezeigt

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/fau-cris#204]
Das Plugin, das Preisträger bzw. Mitgliedschaften in einer Akademie darstellt, zeigt nicht mehr die Bildquelle des Fotos.

Beispielseite hier:
https://www.fau.de/fau/geschichte-und-erfolge/akademie-mitglieder/nationale-akademie-der-wissenschaften-leopoldina/

Folgender Shortcode ist hier eingebaut:
[cris show="awards" awardnameid="186" display="gallery" showname="1" showawardname="0"]

Ein Foto mit Bildquelle hat z.B. Frau Merklein.

**Comment by m-w** [comment]
Der Webservice liefert die Bildquelle weiterhin als Attribut "description" der Relation AWAR_has_PICT aus.

**Comment by cassandre** [comment]
Vorübergehender oder bereits gelöster Fehler.
