### ISSUE TITLE
Bilder werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/fau-cris#205]
Die Bilder aus CRIS werden bei den Auszeichnungen, Preisträgern und Akademiemitgliedern nicht mehr angezeigt.
Beispiele:
https://www.fau.de/fau/geschichte-und-erfolge/akademie-mitglieder/bayerische-akademie-der-wissenschaften-muenchen/
https://www.fau.de/research/ausgezeichnete-einzelforschung/erc-grants/#collapse_0
https://www.fau.de/research/ausgezeichnete-einzelforschung/alexander-von-humboldt-professur/

**Comment by AndiWebred** [comment]
CRIS schreibt dazu:
Der Webservice liefert die Bilder noch aus, intern müsste man direkt auf https://cris.fau.de/ws-cached/1.0/public/infoobject/getrelated/Award/136824873/awar_has_pict (da kommt ein XML) zugreifen können.

**Comment by m-w** [comment]
Das Problem scheint aber globaler Natur zu sein. Bilder zu Forschungsbereichen werden auch nicht mehr angezeigt, Bsp: https://www.lap.physik.nat.fau.de/forschung-weber/graphen/

**Comment by m-w** [comment]
Die Daten aus dem Webservice enthalten auch weiterhin ein PNG-Bild (Attribut "png180"), dessen Informationen wie bisher base64 codiert sind.

**Comment by xwolfde** [comment]
Console meldet ein Status 414
https://developer.mozilla.org/de/docs/Web/HTTP/Status/414

=> Die Bilder sind zu groß.

**Comment by xwolfde** [comment]
(Ich hab mal Max und Rolf gefragt ob wir an Server und Loadbalance einstellen können. Aber das ist ein Notbehelf. Warum verwendet ihr denn PNG für Fotos? JPG, auf 85% reduziert, sollte es auch tun)

**Comment by m-w** [comment]
Der Webservice liefert nur Vorschaubilder mit Kantenlänge 180 Pixel aus. Im o.g. Fall sind das 53 kb. PNG wurde gewählt, da insb. bei Projekten und Forschungsbereichen Abbildungen von Skizzen verwendet werden, die JPG zermatscht.

414 ist wahrscheinlich die falsche Fährte, die Bilder werden durch das Plugin inline im HTML zur Verfügung gestellt. Es gibt also gar keinen Server-Request, der zu lang sein kann.

**Comment by xwolfde** [comment]
haben gerade noch weiter geschaut. da Plugin hat ein Aufruffehler. Die Syntax für Inline-Bilder ist:

data:[<mime type>][;charset=<Zeichensatz>][;base64],<Daten>

**Comment by m-w** [comment]
Diagnose: das Prefix "data:" ist bei den inline-Bildern abhanden gekommen.

Richtig: `<img src="data:image/png;base64,ABC...CBA" .../>`
Falsch: `<img src="image/png;base64,ABC...CBA" .../>`

Daher kommt auch der kaputte Server-Request.

**Comment by xwolfde** [comment]
Wir werden mal cris.fau.de mit in die Content-Security-Policy nehmen. Dann wird ein Browser die Bilder auch anzeigen, wenn sie via src="https://cris.fau.de/.."  aufgerufen werden.
Dann braucht niemand wilde Verrenkungen mit Inline-Code machen

**Comment by xwolfde** [comment]
Do it so.

**Comment by m-w** [comment]
> 
> 
> Wir werden mal cris.fau.de mit in die Content-Security-Policy nehmen. Dann wird ein Browser die Bilder auch anzeigen, wenn sie via src="https://cris.fau.de/.." aufgerufen werden.
> Dann braucht niemand wilde Verrenkungen mit Inline-Code machen

Wir haben die Bilder nicht als Files vorliegen, die stecken in einem DMS (bis April 2018 sogar in der Datenbank). Inline wird also erstmal bleiben.

**Comment by m-w** [comment]
Weitere Nachforschungen haben ergeben:

1. Daten aus Webservice unverändert.
1. Plugin nicht verändert.
1. Auf Testseiten funktioniert das ganze.

Der Plugin-Code enthält die fehlende Anweisung:

https://github.com/RRZE-Webteam/fau-cris/blob/d591563375b98b174b37b46b199e8a053d5ca7c1/class_Auszeichnungen.php#L564

https://github.com/RRZE-Webteam/fau-cris/blob/d591563375b98b174b37b46b199e8a053d5ca7c1/class_Forschungsbereiche.php#L230

https://github.com/RRZE-Webteam/fau-cris/blob/d591563375b98b174b37b46b199e8a053d5ca7c1/class_Projekte.php#L424

Damit bleiben folgende Optionen:

1. Die Installation des Plugins auf dem CMS ist defekt.
1. Mit dem Update auf 5.2.4 werden data: URLs seitens WordPress herausgefiltert (unwahrscheinlich wegen oben 3.).
1. Eine andere Anpassung am CMS wirft den data: Prefix weg.

**Comment by cassandre** [comment]
Liegt weder an der Schnittstelle, noch am Plugin, sondern an einem Lazy-Loading-Plugin. Das wird gerade überarbeitet und ist bis dahin deaktiviert.

**Comment by m-w** [comment]
Aus meiner Sicht können wir das Ticket hier schließen, oder?
