### ISSUE TITLE
cris custom: Fehlendes Aufzählungssymbol bei 1 Publikation pro Jahr

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#206]
cris custom zeigt nur dann ein Aufzählungssymbol (o) an, wenn mehr als ein Item im Jahr in der Gliederung vorliegt. Dies weicht von der non-custom version ab und sieht nicht gut aus. Bitte an den Standard anpassen.

Beispiel hier (Jahre 2008, 2004 & 2001ff):

[cris-custom show=publications type=beitrag_fachzeitschrift peerreviewed=1 orgID=105851520]<strong>#title#</strong>
[/cris-custom]

**Comment by BastianMelsheimer** [comment]
English:
cris custom does not show the dot in front of an item when there is only one item in a given group. Example is this:
[cris-custom show=publications orderby=year type=beitrag_fachzeitschrift peerreviewed=1 orgID=105851520]#title#
[/cris-custom]
The bug can be seen in years 2012 and 2008, for example.
Solution: Add a dot, even when there is only one item in a list.

**Comment by aajusah98** [comment]
fixed and updated already on beta branch
