### ISSUE TITLE
Ausgabe von Bildern bei Publikationen

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#208]
An Publikationen können Bilder via PUBL_has_PICT angehängt werden.

Ein Beispiel wäre dieses hier: 
https://cris.fau.de/converis/portal/Publication/123699664?auxfun=&lang=de_DE

Diese sollten per Plugin ausgegeben werden, möglichst konfigurierbar:

- Bildausgabe ja/nein (default nein)
- Bildplatzierung (vor, über, unter dem Eintrag) (eventuell via custom?)

**Comment by cassandre** [comment]
Könnt ihr da auch die description über den Webservice ausliefern? Oder gibt es da keine?

**Comment by cassandre** [comment]
Kann man einer Publikation auch mehrere Bilder zuordnen?

**Comment by BastianMelsheimer** [comment]
Eine Publikation kann maximal 1 Bild angehängt haben.

Eine description gibt es aktuell noch nicht, fügen wir Ende der Woche ein.

**Comment by cassandre** [comment]
> Eine description gibt es aktuell noch nicht, fügen wir Ende der Woche ein.

Ich seh' noch nix. Seid ihr noch nicht dazu gekommen, oder hängt der Webservice?

**Comment by m-w** [comment]
Also eigentlich hatten wir das Attribut angelegt, aber das System gibt es nicht über den Webservice aus. Nächster Versuch am Dienstag...

**Comment by m-w** [comment]
Ich konnte das Attribut doch schon früher anlegen. Für die Publikation 225503709 ist auch ein Text hinterlegt. Wichtig: Die Angabe ist nur einsprachig, daher `language=0`.
