### ISSUE TITLE
Unterschiedliches Accordion Default Verhalten bei Publikation, Auszeichnung und Patent

### ISSUE THREAD

**Issue by Blubbaa** [RRZE-Webteam/fau-cris#209]
Die drei identischen Abfragen mit `format="accordion"` erzeugen jeweils ein Accordion, wobei bei `awards` und `patents` jeweils das erste Jahr geöffnet ist, bei `publications` sind dagegen alle geschlossen.

```
[cris persID="xxxx" show="awards" orderby="year" format="accordion"]

[cris persID="xxxx" show="patents" orderby="year" format="accordion"]

[cris persID="xxxx" show="publications" orderby="year" format="accordion"]
```

Beispiel: [https://www.lte.tf.fau.de/person/robert-weigel/](https://www.lte.tf.fau.de/person/robert-weigel/)

**Comment by Blubbaa** [comment]
Bei Forschungsprojekten, Forschungsbereichen und Forschungsaktivitäten ist ebenfalls jeweils das erste Jahr geöffnet.

**Comment by cassandre** [comment]
Ist im nächsten Update drin.
