### ISSUE TITLE
Status 'current' zeigt altes Projekt an | Zahlendreher in Projektende

### ISSUE THREAD

**Issue by Blubbaa** [RRZE-Webteam/fau-cris#210]
Ich versuche eine Übersicht aller aktuellen Projekte mit dem folgenden Shortcode zu erstellen:
`[cris show="projects" orderby="year" status="current" format="accordion"]`

Leider wird ein abgeschlossenes Projekt aus 2015 - 2017 immer noch angezeigt, das Enddatum zeigt 2107:
![image](https://user-images.githubusercontent.com/10139960/75254462-b047ae80-57e0-11ea-8ac9-7a2f6907370e.png)

Hier der [Link](https://www.lte.tf.fau.de/forschung/projekte/#collapse_3) zur Website, und hier ist der [Link zum Projekt](https://cris.fau.de/converis/portal/Project/126252814) in CRIS, das Jahr ist richtig als 2017 eingetragen.

Wo könnte dieser seltsame Zahlendreher herkommen?

**Comment by cassandre** [comment]
@m-w: Kannst du da mal schauen? Im virtualEndDate steht tatsächlich '2107-12-31' statt '2017-12-31'.

**Comment by m-w** [comment]
Im Jahr 2018 wurde das Jahr von 2107 auf 2017 korrigiert, aber offenbar nicht auf das Attribut `virtualenddate` übertragen. Datensatz ist jetzt neu gespeichert, WS-Cache aktuell. Sollte also jetzt passen.
