### ISSUE TITLE
select shown publications for a research field

### ISSUE THREAD

**Issue by MarkusLohmayer** [RRZE-Webteam/fau-cris#211]
Hallo Zusammen!
Damit unsere Webseite vom LTD endlich auf WP wechseln kann
müssen wir dafür sorgen, dass für jeden Forschungsbereich
alle Publikationen angezeigt werden
mit absteigendem Datum.

Folgender Code funktioniert wunderbar:
```
publications of Johann's project:
[cris show="publications" project="200250097"]
```

Daher würde ich erwarten, dass es auch möglich sein sollte
Publikationen die einem Forschungsfeld zugeordnet sind anzuzeigen.
```
publications pertaining to the motion capturing field:
[cris show="publications" field="201462917"]
```
Leider kommt `No publications found.` als Antwort.
Allerdings gibt es genau eine Publikation in diesem Fall, siehe
[CRIS](https://cris.fau.de/converis/portal/Forschungsbereich/201462917).
Wenn es mehrere Publikationen sind, dann müssen diese wie gesagt alle von neu nach alt sortiert angezeigt werden.

Dieser Anwendungsfall sollte eigentlich von
```
[cris-custom show="fields" field="201462917"]
projects:
#projects#
involved scientists:
#persons#
publications:
#publications#
[/cris-custom]
```
abgedeckt werden vermute ich.
Leider ist es uns auch mit `[cris-custom ...]` nicht möglich einzustellen welche Publikationen wie angezeigt werden!
In der Dokumentation haben wir auch keine Hinweise gefunden wie man die Anzahl, Sortierung, etc. der Publikationen in diesem Fall beeinflussen kann. Uns ist nicht einmal klar nach welchem Schema das Plugin oder CRIS dies erledigt wenn keine weitere Konfiguration vorgenommen wurde.

Für Hilfe wären wir sehr dankbar!

**Comment by cassandre** [comment]
Eine Ausgabe der Publikationen nach Forschungsbereich ist aktuell nur über den Shortcode cris-custom möglich. 
Mit publications_orderby="year" bekommt man eine nach Jahren gegliederte und absteigend sortierte Liste. Analog mit publications_orderby="type" eine nach Publikationstyp gegliederte Liste. 
Mit publications_limit="10" kann man die Liste entsprechend kürzen. Hier entfällt dann die manuelle Sortierung, und die Publikationen werden in der Reihenfolge angezeigt, in der sie dem Forschungsbereich zugeordnet wurden.
