### ISSUE TITLE
Bildbeschreibung Forschungsbereiche

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#215]
Analog zu den Publikationen gibt es eine Bildbeschreibung (wieder nur einsprachig). Diese wird über das Plugin nicht ausgegeben (ich hoffe, ich erzeuge hier kein Duplikat).

**Comment by cassandre** [comment]
Bei sowas sind Beispieldatensätze immer seeehr hilfreich. :-)

**Comment by m-w** [comment]
Da bin ich heute mal großzügig: FOBE ID 142684242 :-)

**Comment by cassandre** [comment]
https://github.com/RRZE-Webteam/fau-cris/commit/f680750a0a1a4b776af21050eb84a9b72868a21a
