### ISSUE TITLE
Sortierung von Publikationslisten

### ISSUE THREAD

**Issue by Blubbaa** [RRZE-Webteam/fau-cris#219]
Wie ja bereits in #157 beschrieben, funktioniert die Sortierung der Publikationen nach Veröffentlichungsdatum in Projekten momentan nicht. 

Allerdings scheinen Publikationen insgesamt momentan standardmäßig nach Nachname statt Veröffentlichungsdatum sortiert zu werden.

Das folgende Beispiel liefert das Accordion nach Typ & Jahr gegliedert, innerhalb eines Jahres aber nach Nachnamen sortiert:
`[cris orgID="105998808" show="publications" start="2018" format="accordion" orderby="type,year"]`

Am nähesten komme ich dem gewollten Ergebnis mit:
`[cris orgID="105998808" show="publications" start="2018" format="accordion" orderby="type,year" sortby="created"]`
Das ist aber ja auch nicht wirklich das was gewollt ist.

**Comment by cassandre** [comment]
Das gewollte Ergebnis erreicht man mit `sortby="virtualdate"`. Allerdings sollte das eigentlich default und damit nicht nötig sein. Ich schaue mir das an und repariere es. Bis dahin muss man eben das Attribut von Hand eingeben.
