### ISSUE TITLE
Sortierung nach Änderungsdatum / Erfassungsdatum

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#22]
Ich möchte Publikationslisten nach Änderungsdatum bzw. Erfassungsdatum (wann wurde der Datensatz initial angelegt) sortieren.

Die Informationen sind in den Daten des Webservice bereits enthalten.

**Comment by cassandre** [comment]
Dafür braucht's dann nur die nicht gegliederte Listenansicht, oder? 
`orderby=type sortby=updatedon` macht nicht viel Sinn, denke ich.

**Comment by cassandre** [comment]
Neu in https://github.com/RRZE-Webteam/fau-cris/commit/e65e9d60ec8d51e5c82b830bf39880d51e15c374:
sortby=created bzw. sortby=updated
