### ISSUE TITLE
Bug: "Portal Forschung" Menü, Zuordnung Projekte zu Forschungsbereichen fehlerhaft

### ISSUE THREAD

**Issue by itodnerd** [RRZE-Webteam/fau-cris#222]
Beim erstmaligen Import der Projekte von CRIS werden diese in die richtigen Kategorien einsortiert.
Beim zweiten Import werden alle Einträge von einigen Projekten, die mehreren Forschungsbereichen zugeordnet sind, in den selben Forschungsbereich verschoben.

Example:

- Erster Import
![Erster Import](https://user-images.githubusercontent.com/66596643/84015478-2f21bb00-a97c-11ea-845d-1fb590d386fd.png)
- Zweiter Import / Aktualisierung
![zweiter Import / Aktualisierung](https://user-images.githubusercontent.com/66596643/84015480-2fba5180-a97c-11ea-91cb-007cbbc7b510.png)

[Siehe Hier](https://www.cs6.tf.fau.de/forschung/)

**Comment by cassandre** [comment]
Ist korrigiert. Danke für den Hinweis!
Dass Projekte mehreren Forschungsbereichen zugeordnet sein können, hatte ich irgendwie nicht auf dem Schirm.
