### ISSUE TITLE
Parallele Abfrage von Datensätzen mit unterschiedlicher ID

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#23]
Ich möchte mit einem Abruf Publikationen mehrerer Organisationen (z.B. zwei Cluster), Personen (z.B. die drei Professoren an einem Lehrstuhl) oder einfach nur 5 Publikationen abfragen. Dopplungen sollen automatisch herausgefiltert werden.

Im Attribut bietet sich die Trennung per Komma (o.ä.) an.

**Comment by cassandre** [comment]
Seit https://github.com/RRZE-Webteam/fau-cris/commit/f3eabd9dd6fda0b5d163ae08c6a45802a35f5de3 möglich.
