### ISSUE TITLE
Laufzeitverlängerung als Platzhalter für Projekte hinzufügen für CRIS Custom Shortcode

### ISSUE THREAD

**Issue by TimonSengewald** [RRZE-Webteam/fau-cris#234]
In Cris kann für Projekte eine Laufzeitverlängerung eingegeben werden. Der Platzhalter #end# sollte daher entweder das tatsächliche Projektende nach Laufzeitverlängerung anzeigen oder es sollten einen eigenständigen Platzhalter Laufzeitverlängerung geben.

**Comment by cassandre** [comment]
Gehe ich richtig in der Annahme, dass der Wert im Feld "Extension Date" liegt?

**Comment by m-w** [comment]
Der Wert an sich ja. Letztlich kannst du das aber auch mit virtualenddate kombinieren (ist immer gefüllt und wird entweder tatsächlich virtuell berechnet oder enthält ordentliche Daten). Wenn das nicht so ist, dann haben wir auf unserer Seite einen Bug.

**Comment by m-w** [comment]
Wenn ein einiger zusätzlicher Platzhalter nicht viel Arbeit macht, dann realisieren. Ansonsten nur das "richtige" Ablaufdatum.

**Comment by cassandre** [comment]
Habe es in https://github.com/RRZE-Webteam/fau-cris/commit/4019170571f00a552df0cb0f4566ad0727438877 folgendermaßen umgesetzt:
- In der Liste gibt es nur Ende (=> Extension Date wenn vorhanden, sonst cfEndDate).
- In der Single-Ansicht werden Ende und Laufzeitende separat angezeigt (wie in CRIS-Webfrontend auch).
- Für Custom-Views (Liste und Single) gibt es neu den Platzhalter `#extend#`.
