### ISSUE TITLE
Publikationen: Anzahl Autoren beschränken

### ISSUE THREAD

**Issue by stierhofj** [RRZE-Webteam/fau-cris#240]
In Bereichen der Naturwissenschaften (hier speziell Astronomie) ist die Liste der Autoren häufig weit über 10. Um Publikationslisten mit vielen Autoren vernünftig darstellen zu können sollte es einen Parameter für die maximale Anzahl der dargestellten Autoren geben. Ich bin in der Dokumentation und im Sourcecode nicht fündig geworden, falls es dafür doch eine Option gibt. Falls nicht, lässt sich das relativ einfach in `make_list()` in _class_Publikationen.php_ ändern indem man `$authors_html` z.B. so ändert
```php
...
    // Use only first $max_num_authors
    if ($max_num_authors > 0 && count($authorList) > $max_num_authors) {
        $authors_html = implode(", ", array_slice($authorList, 0, $max_num_authors)) . " et al.";
    } else {
        $authors_html = implode(", ", $authorList);
    }
...
```
und entsprechend Funktionsaufrufe und die Parameterliste.

**Comment by m-w** [comment]
Spricht etwas dageben, die generierten Zitatationsstile zu nutzen (quotation=apa bzw. quotation=MLA)?

**Comment by stierhofj** [comment]
Wir benutzen aktuell den NASA/ADS service für ältere Publikationen und für neuere CRIS und hatten versucht den output anzugleichen, deswegen kam das Problem überhaupt auf. Die Angabe des letzten Autors ist in der Astronomie zwar nicht üblich, aber quotation=apa löst das Problem. Zumindest wird man nicht mehr von 100ten von Autoren erschlagen.

Wir hatten versucht das mit einem [cris-custom] zu lösen und sind nicht mehr auf die Idee gekommen, die quotations zu benutzen, danke!

**Comment by m-w** [comment]
Welcher Zitierstil wird denn in der Astronomie üblicherweise benutzt, gibt es dazu eine Beschreibung?

**Comment by stierhofj** [comment]
https://www.aanda.org/doc_journal/instructions/aadoc.pdf beschreibt das Format unter 3.6.1 (p. 12). Eine andere Möglichkeit wäre einfach das json der query zurück zu, falls das geht.
