### ISSUE TITLE
Positionierung Abbildung Forschungsbereich custom

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#244]
Seit einem Update wird das Bild zum Forschungsbereich nicht mehr oben, sondern unterhalb der Kontaktangaben gesetzt ([Beispiel](https://www.lap.physik.nat.fau.de/forschung-krstic/elektronische-eigenschaften-von-nanodraehten/)):

```
[cris-custom show=fields field=143]
#image1#
#description#
[/cris-custom]
```

Texte bleiben in der richtigen Spalte.

**Comment by xwolfde** [comment]
Liegt an dem uralten Floating-Layout, welches nicht nur bei CRIS, sondern auch bei anderen Inhaltsblöcken Probleme macht. ggf. könnte es helfen 


Wird ggf. durch Umbauarbeiten zu Flex Grid gelöst: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/731

**Comment by BastianMelsheimer** [comment]
Scheint sich damit erledigt zu haben, zumindest sieht das gut aus: https://www.lap.physik.nat.fau.de/forschung-weber/siliziumkarbid-und-epitaktisches-graphen-elektronische-eigenschaften/
