### ISSUE TITLE
Keine Bilderausgabe in Publikationsliste mit Zitationsstil

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#245]
Die Ausgabe von Bildern in Publikationsliste klappt aktuell nicht zusammen mit einer gewählten quotation:

Funktioniert und zeigt Bilder an:
[cris show=publications orgID=105793482  orderby=year showimage=1]

Zeigt keine Bilder an:
[cris show=publications orgID=105793482  orderby=year showimage=1 quotation=apa]

Kann es sein, dass zur Bilderausgabe auch noch die Dokumentation fehlt?

**Comment by cassandre** [comment]
gefixt in 02d9c3aa209e06107054dbe0d56cfddb2accbe01
