### ISSUE TITLE
Seite wegen Ladeprobleme down

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-cris#247]
Unsere Webseite https://www.nat.fau.de/forschung/cris/ lädt so langsam, dass eine Bearbeitung der Seite nicht mehr möglich ist. Kann man das so programmieren, dass die Publikationen nicht mitgeladen werden, wenn man versucht in Wordpress die Seite zu bearbeiten?

**Comment by m-w** [comment]
Die Seite scheint alle Publikationen von 2018-heute der Fakultät zu laden (Einblick in den Code habe ich allerdings nicht). Wenn meine Vermutung stimmt, müsste das dringend geändert werden. @cassandre kannst du nebenwirkungsfrei die Einbindung anschauen?

**Comment by cassandre** [comment]
Ich habe die Seite mal so bearbeitet, dass jetzt nur noch Publikationen von 2020 angezeigt werden. Zwei Jahre für die gesamte Fakultät sind zu viel (@m-w Es sind pro Jahr insgesamt 5 Abfragen: je eine pro Department).
Ein Jahr dauert auch, funktioniert aber. Ich denke, die neue Plugin-Version ist dann performanter.

**Comment by cassandre** [comment]
P.S.: Das Bearbeiten hat bei mir auch nur mit Trick funktioniert: Das Backend wurde angezeigt, aber der Editor-Inhalt nicht. Aber über die Revisionen habe ich die letzte Version mit nur einem Jahr (2018) wiederhergestellt und konnte dann das Jahr auf 2018 ändern

**Comment by m-w** [comment]
Allgemein sollte man auf Fakultätsebene keine allgemeine Publikationsliste ausgeben, der Nutzen für Externe ist aus meiner Sicht recht gering.

Wir hätten in CRIS sofort einsetzbare Optionen zur Verwaltung von herausragenden Publikationen. Allerdings ist das immer subjektiv, so dass ein Kuratierungsschritt notwendig ist (Annahme/Ablehnung von Vorschlägen der Forschenden). Das muss jemand aus der Fakultät übernehmen - kann auch auf mehrere Schultern verteilt werden, z.B. auf Departmentebene.
