### ISSUE TITLE
Zusätzliche Zeilenumbrüche im Orga-Text

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#249]
Beim Orga-Text auf [dieser Website](https://www.lap.physik.nat.fau.de/forschung/) werden zusätzliche breaks eingefügt. Diese sind in den [Daten des Webservice](https://cris.fau.de/ws-cached/1.0/public/infoobject/get/organisation/105888648) nicht vorhanden.

**Comment by cassandre** [comment]
Das Problem hatten wir schonmal. War ein Copy/Paste-Problem. Ich schau mal, dass ich den Issue finde.

**Comment by m-w** [comment]
Das hatte ich auch erst gedacht und in CRIS den Text komplett ohne Formatierung eingespielt. Daher finden sich die Umbrüche eben auch nicht in den Daten aus dem Webservice, sondern tauchen unverhofft auf.

**Comment by m-w** [comment]
Oder meinst du in der Website selbst beim Shortcode? Für diesem Fall noch die Info, dass die Physik die Synchronisierung nutzt.

**Comment by cassandre** [comment]
Doch. Wenn ich den Text direkt aus dem [Webservice](https://cris.fau.de/ws-cached/1.0/public/infoobject/get/Organisation/105888648) in einen Plain-Text-Editor kopiere, sieht er folgendermaßen aus:
![Bildschirmfoto 2021-02-08 um 15 07 06](https://user-images.githubusercontent.com/4435815/107230541-7dadba80-6a1f-11eb-9a9f-bf0463c295bc.png)
Da sind also die Umbrüche schon drin, ohne dass der Inhalt jemals mit dem Plugin in Berührung gekommen wäre.

**Comment by cassandre** [comment]
In dem Fall sind es `\r`. Ich schau mal, dass ich `\r` und `\n` grundsätzlich aus den Texten entferne.

**Comment by cassandre** [comment]
Wäre allerdings auch nicht verkehrt, wenn ihr die schon im CRIS-Editor entfernen könntet oder sichtbar machen, dass es einem bei der Eingabe direkt auffällt.

**Comment by m-w** [comment]
Leider sind wir in Sachen Editor machtlos. Ich habe jetzt hoffentlich über den Umweg "vi" und hexdump alle Zeichen rausgeworfen, welche nicht reingehören. Danke für die Diagnose.
