### ISSUE TITLE
BibTeX-Download von Publikationsdaten

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#25]
Der Webservice liefert nun im Attribut "bibtex_link" direkt einen HTML-Link zu den BibTeX-Daten. Alternativ lautet dieser immer "http:/ /cris.fau.de/bibtex/publication/__ID__.bib", wobei "__ID__" die Nummer des Datensatzes ist.

Das ist doch was für's Plug-In, oder?

Der BibTeX-Export ist auch für Personen und Lehrstühle/Professuren möglich, siehe http://blogs.fau.de/cris/2016/05/04/forschungsportal-jetzt-mit-bibtex-export/

**Comment by cassandre** [comment]
Klar. Für einzelne Publikationen? Oder die gesamte Liste? Oder beides?
Auf jeden Fall würde ich es in den Optionen einstellbar machen, ob man den Link auf der Seite zur Verfügung stellen möchte.

**Comment by cassandre** [comment]
Ah, ihr liefert den bibtex_link gleich mit über die Schnittstelle. Sehr schön. Spielt. 
Soll der BibTeX-Link bei allen Darstellungen (standard, MLA und APA) mit rein?

**Comment by cassandre** [comment]
Is drin: https://github.com/RRZE-Webteam/fau-cris/commit/344fe9719e5c9e0969e0917b252abd5994084cef

**Comment by cassandre** [comment]
In Version 1.8 (https://github.com/RRZE-Webteam/fau-cris/commit/1bc8502886a2b894a4f7fc8d1d3795da0d4cf784) drin.
