### ISSUE TITLE
CRIS-Custom Dokumentation für Equipment fehlt

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#250]
Siehe Betreff:

https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/fau-cris/erweiterte-optionen/

**Comment by cassandre** [comment]
Erledigt: https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/fau-cris/erweiterte-optionen/#collapse_4
