### ISSUE TITLE
Patentabruf für Person klappt nicht

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#252]
Die Abrufe

[cris show="patents" persID="248294705"]
[cris show="patents" orgID="246839335"]

sollten das gleiche Ergebnis liefern, aktuell liefert aber nur die Orga-Abfrage, die Personenabfrage ist leer.

**Comment by m-w** [comment]
Der [Webservice](https://cris.fau.de/ws-cached/1.0/public/infoobject/getautorelated/person/248294705/pers_2_pate_1) liefert für die Person nichts. Liegt also eher nicht am Plugin.

**Comment by m-w** [comment]
Für eine andere [Person](https://cris.fau.de/ws-cached/1.0/public/infoobject/getautorelated/person/103671142/pers_2_pate_1) klappt es aber.
