### ISSUE TITLE
CSS/JS nun bei Bedarf einbinden

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-cris#26]
Das CSS von CRIS wird auf jeder Seite eingebunden, auch wenn auf der gar kein Shortcode für CRIS vorhanden ist:

&lt;link rel='stylesheet' id='cris-css'  href='/wp-content/plugins/fau-cris/css/cris.css?ver=4.5.2' type='text/css' media='all' /&gt;

Bitte nur dann den CSS in den Header (und ggf. JS in den Footer?) wenn auf der jeweiligen Siete CRIS auch tatsächlich benötogt wird.

**Comment by cassandre** [comment]
Is drin: https://github.com/RRZE-Webteam/fau-cris/commit/344fe9719e5c9e0969e0917b252abd5994084cef
