### ISSUE TITLE
Automatisches Erstellen von Einträgen und das neue Theme sorgt für Darstellungsprobleme

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-cris#267]
Bin gerade auf meiner Testinstanz über ein mögliches Problem mit dem neuen Theme gestolpert:

Wenn man in den CRIS-Einstellungen automatisch die Forschungsseiten generiert, dann fängt das neue Theme an zu streiken.
Das Logo verschwindet und die Inhaltsseiten bleiben für den Endnutzer leer.

# Nur auf Testinstanz bis jetzt getestet
Bis jetzt habe ich das ganze nur auf meiner Testinstanz mit WordPress 5.8.3 getestet.

# Darstellung in Safari & Chrome:
https://www.urlaubaufsagrotan.test.rrze.fau.de/forschung/betriebssysteme/invasives-laufzeitunterstuetzungssystem-irtss-c01/
<img width="2221" alt="Bildschirmfoto 2022-01-14 um 09 36 05" src="https://user-images.githubusercontent.com/58593037/149482064-ef6006b4-05a2-41f7-aeae-dc3a58c4a91d.png">

# Darstellung der Forschungs-Portalseite wie erwartet:
https://www.urlaubaufsagrotan.test.rrze.fau.de/forschung/
<img width="2221" alt="Bildschirmfoto 2022-01-14 um 09 36 20" src="https://user-images.githubusercontent.com/58593037/149482328-33d8f0a5-d056-4563-bbbd-af666e07e838.png">

# Darstellung der Shortcodes im Backend-Editor wie erwartet:
https://www.urlaubaufsagrotan.test.rrze.fau.de/forschung/betriebssysteme/invasives-laufzeitunterstuetzungssystem-irtss-c01/

# Einstellungen:
<img width="1123" alt="Bildschirmfoto 2022-01-14 um 09 39 39" src="https://user-images.githubusercontent.com/58593037/149481857-07c18e4e-8153-4458-9e08-ab5dac46a07d.png">
<img width="1110" alt="Bildschirmfoto 2022-01-14 um 09 39 30" src="https://user-images.githubusercontent.com/58593037/149481873-53858e0e-087a-4838-ae49-1cd28eedca16.png">

**Comment by xwolfde** [comment]
Ich vermute mal, dass in CRIS ein Template der Seite vorhanden ist, welches aktualisiert werden muss

**Comment by m-w** [comment]
Aus CRIS selbst kommt nur XML ohne jegliche Formatierung (Ausnahme sind Zitatangaben, die enthalten teilweise noch ein ```<i>journalname</i>```).

**Comment by cassandre** [comment]
War ein PHP-Fehler, kein Template-Problem.
In e4fb129318b5969793851088b60692bbafce305d erledigt.
