### ISSUE TITLE
Publikationsliste einer Organisation/OrgID unvollständig

### ISSUE THREAD

**Issue by benemoto** [RRZE-Webteam/fau-cris#27]
Ich möchte eine vollständige Liste aller Publikationen (eines Jahres) unseres Instituts anzeigen lassen. Im Prinzip erst einmal genau so wie das hier gemacht ist:
 https://cris.fau.de/converis/publicweb/Organisation/142218?share=false&cntpers=false&reqstfulltxt=false&reports=false&lang=1  (allerdings erst mal ohne Seitenblätter-Funktion). 

Als Shortcode gebe ich `[cris year="2015" orgid="142218"] `an.

Ich bekomme aber nur 4 Publikationen angezeigt, obgleich im System offenbar 16 Eintragungen für das Jahr 2015 vorhanden sind (siehe Link oben).

Was mache ich falsch, bzw. liegt hier ein Fehler vor?

**Comment by cassandre** [comment]
Vielleicht ein Cache-Problem des Browsers. Ich bekomme bei dem identischen Shortcode >50 Publikationen angezeigt (temporärer Link: http://www.test.rrze.uni-erlangen.de:2175/cris-publikationsliste/). Hilft ein Neuladen der Seite?

**Comment by benemoto** [comment]
Ich hatte bereits einige Male aktualisiert. Ich weiß zwar nicht genau wo der Fehler lag, aber nachdem ich den Shortcode auf eine andere Seite gesetzt habe, hat es funktioniert: http://www.geographie.nat.uni-erlangen.de/publikationen-des-instituts/

Evtl. ein Problem der Wordpress Page-Cache Funktion.

**Comment by cassandre** [comment]
Das mag sein. Sie scheinen ja eine eigene WP-Instanz zu haben; da weiß ich nicht, wie der Cache funktioniert. Auf der von Ihnen verlinkten Seite sehe ich allerdings jetzt alle Publikationen, ohne die Einschränkung auf 2015. Aber wenn Sie sagen, es funktioniert, glaube ich Ihnen das mal... ;-)

**Comment by benemoto** [comment]
Das war beabsichtigt. Trotzdem noch eine Frage: Seltsam ist vielleicht nur noch, dass die Reihenfolge nicht nach Alphabet oder einem sonstigen ersichtlichen System zu funktionieren scheint sondern eher "durcheinander".

**Comment by cassandre** [comment]
Die Publikationen müssten nach Publikationsdatum absteigend sortiert sein. D.h. die neuesten (Jahr und Monat – lässt sich im CRIS-Backend eingeben) sortiert.

**Comment by mklotz29** [comment]
Ich habe das gleiche Problem: Publikationen einer Organisation aus CRIS (141443) werden nur teilweise angezeigt.

CRIS: [https://cris.fau.de/converis/publicweb/Organisation/141443?share=false&cntpers=false&reqstfulltxt=false&reports=false&lang=1](https://cris.fau.de/converis/publicweb/Organisation/141443?share=false&cntpers=false&reqstfulltxt=false&reports=false&lang=1)

WP: [https://anglistik.cms.rrze.uni-erlangen.de/fields_of_study/english_linguistics/chair-of-english-linguistics-prof-herbst/publications/](https://anglistik.cms.rrze.uni-erlangen.de/fields_of_study/english_linguistics/chair-of-english-linguistics-prof-herbst/publications/)

Verwendeter Shortcode: [cris show=“publications“ orgID="141443" quotation="apa"]

Was ist falsch?

**Comment by mklotz29** [comment]
Einträge aus CRIS werden jetzt vollständig dargestellt. Kann es sein, dass das Plugin einfach ein bisschen Zeit braucht, um alle Einträge einzulesen?

**Comment by cassandre** [comment]
Sowohl WordPress als auch CRIS haben einen Cache – es kann immer sein, dass irgendwo noch der alte Datenbestand hängt. Den WordPress-Cache der Seite kann man von Hand löschen (bei CMS-Instanzen des RRZE), der CRIS-Cache wird alle paar Stunden erneuert. Dann sollte sich das Problem erledigt haben.
