### ISSUE TITLE
Darstellung der CRIS Publikationsliste

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-cris#271]
Darstellung der Publikationensliste  (https://www.wtm.tf.fau.de/forschung/publikationen/) aus CRIS : Die Links auf die Publikationen werden nicht sauber umgebrochen (getrennt).

( 🎫 http://go.fau.de/9s-ck | Aus Helpdesk )

**Comment by BastianMelsheimer** [comment]
Die Publikationslist des WTM sieht inzwischen richtig aus, der Fehler wurde scheinbar behoben.
