### ISSUE TITLE
Daten aus CRIS (Preise und Auszeichnungen) werden nicht mehr auf der Webseite angezeigt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/fau-cris#280]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/9526974/224689943-fb64bf3d-8d04-4af4-9e1f-fc4266c69065.png">

**Comment by m-w** [comment]
Untersuchung läuft.

**Comment by m-w** [comment]
Ursache ist ein Security-Fix im Webserver: https://github.com/apache/httpd/commit/d78a166fedd9d02c23e4b71d5f53bd9b2c4b9a51

**Comment by m-w** [comment]
Läuft wieder.
