### ISSUE TITLE
Wordbreak-All aktiv?

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#296]
![grafik](https://github.com/RRZE-Webteam/fau-cris/assets/35534665/62bfb0c4-7ea4-485f-81d6-344f4e61ba52)

"Wordbreak-Break All" sorgt im CSS für hässliche Wordbreaks. Kann das geändert werden oder gibt es aus FAU CMS-Sicht einen Grund dafür?

**Comment by rvdforst** [comment]
Nein, es gibt keinen offensichtlichen Grund, word-break: break-all; zu verwenden.
