### ISSUE TITLE
Anzahl der angezeigten Pubs

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-cris#3]
EIn Wunsch aus dem Kurs (mehrheitlich) war auf jeden Fall, die Anzahl zu begrenzen (anzahl="x")
und zeige die letzten 5 Pubs (latest="x")

**Comment by j-hofmann** [comment]
+1

**Comment by cassandre** [comment]
Ist auf jeden Fall praktisch, allerdings schwierig umzusetzen: Wenn ich 10 Publikationen aus dem Jahr 2015 habe, welche 5 soll ich dann anzeigen? Die zuletzt eingetragen wurden? Das sind aber nicht zwangsläufig die, die zuletzt publiziert wurden. 

Ggf. ergänzen die CRIS-Leute noch den Monat der Veröffentlichung in der Datenbank, dann lässt sich das schon eher umsetzen.

Workaround, wenn sich an der Liste auf absehbare Zeit sowieso nichts ändert: 5 Einzelpublikationen ausgeben lassen.

**Comment by j-hofmann** [comment]
Das stimmt natürlich, mit dem Workaround habe ich es jetzt auch gemacht. Einfacher wär natürlich automatisch... ;-) Allerdings: die letzten 5 eingetragenen Publikationen wären m.M.n. auch so hilfreich. Ich weiß nicht, ob der Aufwand, Cris zu erweitern _und_ die User zum Eintragen von noch mehr Daten zu erziehen es wert ist, dann eine minimal richtigere Ausgabe zu bekommen.
Einsatzziel ist sicher auch bei den Kursteilnehmern eine Seite, die nur einen Auszug "recht" aktueller Forschungsbemühungen geben soll, aber ohne tatsächliche Contentänderung trotzdem aktuell aussehen soll: http://www.wi2.fau.de/research/

**Comment by m-w** [comment]
Wir werden demnächst ein Attribut zur Sortierung einführen. Wenn ein Datum/Monat vorliegt, dann wird dieses benutzt. Bei Fehlen desselben landen die Arbeiten nach Erfassungsreihenfolge in der Liste - jedoch immer hinten denen mit Datumsangabe.

**Comment by csw-** [comment]
Wie ist denn hier nun mittlerweile der Status? Eine Limitierung der angezeigten Objekte wäre auch unsererseits (FB Wiso) sehr wünschenswert. (latest XY)

**Comment by benemoto** [comment]
Für das Institut für Geographie benötigen wir ebenfalls eine Reduzierung der Anzeige durch Datum/Monat der Publikation. Kann man nun statt dem Jahr auch den Monat angeben? Und falls ja, wie ist der genaue Syntax?

**Comment by cassandre** [comment]
Ist in der neuesten Version (1.8, https://github.com/RRZE-Webteam/fau-cris/commit/1bc8502886a2b894a4f7fc8d1d3795da0d4cf784) drin.
