### ISSUE TITLE
Show additional information within a project accordion and make it customizable

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#300]
Currently, the short description for a project is shown in an accordion, when a project is listed within e.g. a research field.

[cris show=fields field=142681026]

Add additional details here:

Startdate-Enddate
Project leader (with details from contacts if possible)

Add tag: projects_hide=leader,date,abstract

**Comment by aajusah98** [comment]
The below code is implemented with projects_hide, an attribute which  have four values, funding,leader,date,abstract
[cris show=fields field="142681026" projects_hide="funding,leader,date,abstract"]

**Comment by aajusah98** [comment]
Project leader (with details from contacts have been updated )

project_hide="card", is used to hide the contact details of the leader .

**Comment by BastianMelsheimer** [comment]
Live in 3.23.2
