### ISSUE TITLE
Improve single project display

### ISSUE THREAD

**Issue by BastianMelsheimer** [RRZE-Webteam/fau-cris#301]
Two things should be improved when displaying a single project (e.g. [cris show=projects project=318047798]):

* Remove the "Publications" heading if there are no publications
* Add Externe Partner / External Partners, displaying attribute "Name" from relations PROJ_has_EORG

**Comment by BastianMelsheimer** [comment]
* Heading change is fixed in commit bda1487
* External Partners still open

**Comment by aajusah98** [comment]
updated the code and fixed the issue for external partner, 
 The shorted codes I used to test are :
1) [cris show=projects project=246416478 hide="externalpartners"]
2) [cris show=projects project=318047798 hide="details,externalpartners,abstract"]
