### ISSUE TITLE
Change target links into CRIS' research portal

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#316]
The new portal has a different link architecture. Though all former links are redirects, the plugin should use the new ones.

Examples:
- old: https://cris.fau.de/converis/portal/Person/104013848
- new: https://cris.fau.de/persons/104013848/

You need to go through the plugin and check all outgoing links generated.

----

Complete overview of changed names for detail pages (generated from apache, not all used in plugin), first column is `old`, 2nd is `new`:

- activity activities
- Activity activities
- Award awards
- Award%20type awards/types
- cfrespat patents
- cfResPat patents
- external%20organisation organisations/ext
- External%20Organisation organisations/ext
- External+Organisation organisations/ext
- ExternalOrganisation organisations/ext
- forschungsbereich researchAreas
- Forschungsbereich researchAreas
- Funding%20source funding_sources
- Funding+source funding_sources
- Fundingsource funding_sources
- Invention inventions
- journal journals
- Journal journals
- Nationality nationalities
- nationality nationalities
- Organisation organisations
- person persons
- Person persons
- project projects
- Project projects
- publication publications
- Publication publications
- standardization standards

**Comment by aajusah98** [comment]
The links found and changed inside our plugin are listed below 
- activity activities
- Activity activities
- Award awards
- cfrespat patents
- cfResPat patents
- forschungsbereich researchAreas
- Forschungsbereich researchAreas
- person persons
- Person persons
- project projects
- Project projects
- publication publications
- Publication publications
- standardization standards

The links not found in our plugin are :
- Award%20type awards/types
- external%20organisation organisations/ext
- External%20Organisation organisations/ext
- External+Organisation organisations/ext
- ExternalOrganisation organisations/ext
- Funding%20source funding_sources
- Funding+source funding_sources
- Fundingsource funding_sources
- Invention inventions
- journal journals
- Journal journals
- Nationality nationalities
- nationality nationalities
- Organisation organisations

**Comment by BastianMelsheimer** [comment]
Done in 3.23.2
