### ISSUE TITLE
Filter nach Typ wird nicht ausgeführt

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#32]
Hier sollten nur Bücher erscheinen, es werden jedoch alle Typen ausgegeben:

[cris type="buecher" show="publications" orgID="141483"]

**Comment by m-w** [comment]
Es ist auch das Webbaukasten-Plugin betroffen.

**Comment by cassandre** [comment]
Fixed in https://github.com/RRZE-Webteam/fau-cris/commit/6493ac272978cb7aa740741c347b72024b795d5b.
Merge in master kommt mit nächstem Versionsupdate.
