### ISSUE TITLE
Filter auf type bei Preisen/Auszeichnungen defekt

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#33]
Der Shortcode [cris show="awards" orgid="142351" orderby="type" type="preise"] liefert keine Daten. Entfernt man die Einschränkung des "type", so werden Daten geliefert.

**Comment by cassandre** [comment]
Fixed in https://github.com/RRZE-Webteam/fau-cris/commit/6493ac272978cb7aa740741c347b72024b795d5b
Merge in master kommt mit nächstem Versionsupdate.
