### ISSUE TITLE
Daten eines Forschungsprojektes aus CRIS auslesen

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#38]
Ich würde gerne die Daten, wie sie mir in CRIS angeszeigt werden über einen Shortag im Wordpress einbinden (sowas wie [projectID=12346].
Der Idealfall wäre, wenn ich dann auch noch auswählen könnte (über Shortags), welche Informationen ich haben will (Titel, Details, Abstract, zugehörige Publikationen etc).

**Comment by cassandre** [comment]
Ist in Arbeit. Sobald die Forschungsprojekte über den Webservice ausgegeben werden, werden die Plugins dahingehend erweitert.

**Comment by cassandre** [comment]
Update: Erster Zwischenstand hier: 
http://www.test.rrze.uni-erlangen.de:2175/cris-projekte/
http://www.test.rrze.uni-erlangen.de:2175/cris-projekte/order/
http://www.test.rrze.uni-erlangen.de:2175/cris-projekte/filter/
http://www.test.rrze.uni-erlangen.de:2175/cris-projekte/ids/
Ich freue mich über Feedback. Darstellungswünsche können ggf. jetzt auch noch berücksichtigt werden. ;-)
Falls Sie eine eigene WP-Installation haben, können Sie den aktuellen Stand auch im [dev-branch]  (https://github.com/RRZE-Webteam/fau-cris/tree/dev) herunterladen und testen.

**Comment by cassandre** [comment]
P.S.: Das mit dem Filtern und Sortieren nach Jahren wird noch schöner...

**Comment by xwolfde** [comment]
Hm... zwei Dinge fallen mir auf:
- schema.org-Attribute (z.B. bei Laufzeiten) sind nicht verwendet.
- Du hast einen neuen typos von Accordion geschaffen. ("Details") Warum? Wir haben doch schon ein Accordion-Stil, den wir überall durchziehen . Wäre IMHO besser, wenn ein Accordion immer gleich aussieht und gleich funktioniert

**Comment by cassandre** [comment]
schema.org kommt noch. Wollte ich alles in einem Aufwasch machen. Fehlt bei den Publikationen etc. auch noch.
Zum Accordion: Hatte ich auch überlegt, aber das ist kein Accordion, da es nur ein einziges Element zum Aufklappen gibt: den Abstract. Ein Accordion besteht immer aus mehreren Elementen. Und von der Gestaltung her wäre ein so breiter Balken wie eine Accordion-Überschrift an der Stelle auch deplaziert.

**Comment by FlorianFiller** [comment]
Scheint wohl - zumindest bei "externem" Zugriff ein Problem zu geben:

![error](https://cloud.githubusercontent.com/assets/12810141/17211418/ad1106f8-54c9-11e6-9e05-00b9fa80e430.png)

**Comment by cassandre** [comment]
Nee, sorry, da hatte ich kurzfristig einen Tippfehler drin  (ist gleichzeitig meine Entwicklungsumgebung, da passiert das manchmal). Spielt jetzt wieder.

**Comment by cassandre** [comment]
Ergänzung: http://www.test.rrze.uni-erlangen.de:2175/cris-projekte/display/
Folgende Elemente lassen sich per shortcode ausblenden: Details, Abstract, Publikationen, CRIS-Link

**Comment by cassandre** [comment]
Forschungsprojekte sind in der neuen Version drin: https://github.com/RRZE-Webteam/fau-cris/pull/46
