### ISSUE TITLE
Verknüpfung mit FAU-Person 

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-cris#39]
Die Verknüpfung mit der Kontakte-Datenbank scheint nicht immer zu funktionieren, zumindest in diesem Fall: 

Es ist eine Publikation in CRIS gelistet: 

Amende M, Gleichweit C, Xu T, Höfert O, Koch M, Wasserscheid P, Steinrück H, Papp C, Libuda J:
Dicyclohexylmethane as a Liquid Organic Hydrogen Carrier: A Model Study on the Dehydrogenation 
... etc... 

Für Herrn Steinrück sind zwei Einträge in der Kontakte-Datenbank. Allerdings steht dort jeweils sein voller Name (Hans-Peter Steinrück), während er in obigem Beispiel nur mit "Steinrück H" geführt wird. Andere Doppelnamen (Gensberger-Reigl S) werden korrekt erkannt. Der zweite Eintrag existiert (noch) als Entwurf. Liegt es vielleicht daran? Erkennen die Plugins den Unterschied zwischen Entwurf und veröffentlicht nicht?

**Comment by cassandre** [comment]
Stimmt, Entwürfe wurden mit ausgeliefert und haben den Fehler verursacht (Doppelnamen sind kein Problem). 
Behoben in https://github.com/RRZE-Webteam/fau-cris/issues/39, Update auf den CMS-Instanzen im Laufe des Tages.
