### ISSUE TITLE
Publikationen anhand einer oder mehrerer "Focus Areas" anzeigen/filtern

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-cris#45]
Derzeit kann man ja bereits nach orgID und persID filtern. Eine Ergänzug um die "Focus Areas" wäre wünschenswert. (Ebenso wie nach "Major Research Areas")

**Comment by m-w** [comment]
Da es mittlerweile die Forschungsbereiche gibt (siehe auch #108), wäre das ein möglicher Ersatz?

**Comment by m-w** [comment]
Funktioniert mit `cris-custom`, Doku folgt.

**Comment by cassandre** [comment]
Done.
