### ISSUE TITLE
Sortiermöglichkeiten

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/fau-cris#49]
Wenn ich alles richtig verstehe, kann ich aktuell über das CRIS-PlugIn nur eine Sortierung vornehmen. Wir würden aber gerne mehrere Sortierungen hintereinander einbauen, im konkreten Fall eine Liste sortiert nach Publikationstyp (aktuell umgesetzt durch: orderby="type") und anschließend alphabetisch nach (Erst-)Autor.
Aktuell sind die einzelnen Publikationen eher durcheinander, wohl nach Datum des Anlegens in CRIS o.ä.

Beispiel: https://www.phil.fau.de/forschung/forschungsberichte/

**Comment by cassandre** [comment]
Innerhalb eines Typs werden die Publikationen chronologisch abwärts sortiert: wenn vorhanden nach dem genauen Publikationsdatum (Jahr-Monat-Tag); bei gleichem oder fehlendem exakten Datum wahrscheinlich in der Tat nach Reihenfolge der Erfassung.

Ich werde das Plugin so anpassen, dass man auch eine zweite Sortierung angeben kann (orderby="type, year" bzw. orderby="type, author"). Das sollte recht bald umgesetzt sein, ich weiß allerdings nicht, wann ich das auf den CMS-Instanzen aktualisieren kann – im Moment streikt unser Plugin-Update-Plugin.

**Comment by cassandre** [comment]
In Commit https://github.com/RRZE-Webteam/fau-cris/commit/d7c31c7b6d53d59f8493529bed9e45e509148731 drin:
orderby=“year, author“ ist jetzt möglich, ebenso wie orderby="year, date"

**Comment by BastianMelsheimer** [comment]
Hier klappt das noch nicht, scheinbar: 

`[cris show="publications" quotation="apa" display="no-list" project="239386743,239753833,239387192,239387475,239387778,239421469,239422861,239423685,239423951,239424405,239424652,239424905,237784360,239425161,239425716,239754249,239425985,239426234,239426575,238780714,239427144,239426900"]`

Und ich habe noch keine Dokumentation dazu gefunden :)

**Comment by m-w** [comment]
reopen

**Comment by BastianMelsheimer** [comment]
Aktueller default: Antichronologisch, Alphabetisch nach Erstautor
Soweit sieht das eigtl alles fertig aus, muss aber so noch in die Dokumentation.
