### ISSUE TITLE
Fehler beim Einlesen der Daten: Bitte überprüfen Sie die CRIS-ID

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-cris#5]
Ich erhalte obige Fehlermeldung, obwohl die CRIS-ID richtig angegeben wurde im Backend unter Einstellungen -> CRIS. 

Siehe auch: https://test.nat.fau.de/forschung/cris/ 

Hatte auch schon einmal funktioniert, nur seit ein paar Tagen kommt immer die gleiche Fehlermeldung... obwohl ich an den Einstellungen / Shortcodes nichts geändert habe.

**Comment by cassandre** [comment]
Hm, das scheint nur auf der Multisite ein Problem zu sein, in der Testumgebung funktioniert es. Ich werde am Montag mal nachschauen. Interimslösung: die Organisations-ID als Parameter mit in den Shortcut schreiben: [cris year="2015" orgid="123456"] (ich habe mir mal erlaubt, das auf der genannten Seite auszuprobieren).

**Comment by cibsell** [comment]
Das funktioniert leider auch nicht. Die Org-ID der Fakultät ist 142105. Damit erhalte ich aber oben genannte Fehlermeldung. Es funktioniert nur, wenn man eine andere Org-ID eingibt (Sie hatten 142208 eingefügt).

**Comment by benemoto** [comment]
Ich hatte die gleiche Fehlermeldung und bin nach langem Verzweifeln darauf gekommen, dass es an den falschen Anführungszeichen im Tag lag. Irgendwie hat meine Tastatur oder der WYSIWYG Editor statt den neutralen Anführungszeichen ("), echte typographische Anführungszeichen(“) eingefügt. Dadurch konnte der Tag nicht mehr ausgelesen werden.

**Comment by cassandre** [comment]
Shortcodes sollte man immer in der Text-Ansicht eingeben, da der WYSIWIG-Editor in der Tat genau diesen Fehler verursacht – das ist leider ein typisches WordPress-Problem.
