### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by StephenKoetzing** [RRZE-Webteam/fau-cris#51]
Die Übersetzungen im Plugin sind teilweise fehlerhaft und zudem uneinheitlich.

Falsch ist:
- "Editorials" für "Herausgeberschaften". Es muss "Edited Volumes" heißen (bei der ÜS für die Sammelbandbeiträge ist es übrigens richtig gelöst).
- der Singular "Thesis" im pubTitles-array. Der Plural wäre "Theses", wobei es ohnehin fraglich ist, wie sinnvoll diese Bezeichnung ist, da sie im Englischen eigentlich immer mit Spezifizierung verwendet wird (z.B. MA thesis).

Uneinheitlich ist die Groß-/Kleinschreibung (z.B. "Journal articles" vs. "Articles in Edited Volumes"). Da diese Bezeichnungen für Überschriften verwendet werden, wäre m.E. eine Großschreibung sinnvoll, Kleinschreibung nur bei Artikeln, Präpositionen, etc. (s. MLA Handbook).

Unklar ist mir, wofür das Array pubNames verwendet wird. Es fällt aber auf, dass hier alle englischen Bezeichnungen im Singular gehalten sind, während die Deutschen alle im Plural sind. Absicht?

**Comment by cassandre** [comment]
In der aktuellen Version 3.0 gefixed (https://github.com/RRZE-Webteam/fau-cris/commit/d7c31c7b6d53d59f8493529bed9e45e509148731#diff-fc4534ea8344197e1917519442ece6db).
