### ISSUE TITLE
Projekte ohne Datumsangabe -> 1.1.1970

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#53]
Projekte ohne spezifizierte Laufzeit werden vom Plug-In auf den 1.1.1970 gelegt.

https://cris.fau.de/converis/publicweb/Project/102029 vs.
http://cris-demo.zuv.fau.de/testseiten-fuer-organisationen/235-2/

Projekte ohne Startdatum sortieren wir jetzt aus, das wird ein Pflichtfeld. Die Information über das Projektende ist aber oft nicht vorhanden/bekannt/gesetzt (also auch weiterhin kein Pflichtfeld). Darauf brauchen wir also einen Test.

**Comment by m-w** [comment]
Ggfs. noch abwarten, was mit "virtualenddate" passiert, wenn das Startdatum Pflichtfeld wird. Eventuell erledigt sich das dann von allein.

**Comment by cassandre** [comment]
Da habe ich jetzt bei den Aktivitäten was eingebaut, was das abfängt und das Datum je nach vorhandenen Informationen darstellt: "01.02.2013 - 31.02.2013" oder "seit 01.02.2013" oder "bis 31.12.2013" oder gar nicht. Das baue ich hier dann auch ein.

**Comment by cassandre** [comment]
Ist im nächsten Update mit drin.
