### ISSUE TITLE
Reihenfolge Publikationen am Projekt

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#54]
Die Reihenfolge der Publikationen an einem Projekt kann intern in CRIS vorgegeben werden. Der Webservice gibt die Arbeiten dann auch in dieser Sortierung aus.

Wir müssen prüfen, ob der Abruf durch `by_project` diese Sortierung behält oder ein bisheriger Standard dazwischenfunkt.

**Comment by cassandre** [comment]
Kannst du mir mal ein Beispielprojekt mit sortierten Publikationen schicken?

**Comment by cassandre** [comment]
Die Publikationen bleiben in der Reihenfolge, in der sie vom Webservice ausgeliefert werden.
