### ISSUE TITLE
Neuer Publikationstyp: Unveröffentliche Arbeiten

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#55]
Für wissenschaftliche Veröffentlichungen, welche noch nicht veröffentlicht sind, gibt es nun einen separaten Publikationstyp.

Bsp: https://cris.fau.de/converis/publicweb/Publication/1049182

Im Webservice ist das neue Attribut "publStatus" enthalten, dieses umfasst:

* Submitted / Eingereicht
* In review / Im Review-Prozess
* Accepted / Akzeptiert
* In press / Im Druck
* Published / Veröffentlicht (eigentlich unsinnig, da dann der Typ nicht mehr stimmt)

Ebenfalls im Webservice gibt es "FuturePublicationType", dessen Inhalt ist gleich der bekannten Publikationstypen.

**Comment by cassandre** [comment]
Im nächsten Update mit drin.
