### ISSUE TITLE
Doku ergänzen: Wie komme ich an die ID der Organisation bzw. der Person?

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#56]
Ich habe gerade den Hinweis bekommen, dass in der Doku des Plug-Ins die Information fehlt, wie man an die IDs kommt. Vielleicht kann man sich daran orientieren:

http://cris-demo.zuv.fau.de/testseiten-fuer-personen/testseite-fuer-personen-prof-hornegger/
http://cris-demo.zuv.fau.de/testseiten-fuer-organisationen/testseite-lehrstuhl-fuer-informatik-5-mustererkennung/

**Comment by cassandre** [comment]
Hmm, stimmt. Ist zwar erläutert, aber erst später, bei den Einstellungen.

**Comment by cassandre** [comment]
Ich habe die Info jetzt relativ weit oben und mit Hinweis-Symbol eingefügt.
