### ISSUE TITLE
Zugriff/Darstellung von einzelnen Arrays/Variablen des CRIS-Projekt-Datensatzes

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#57]
Aktuell kann man mit dem plugin zwar einzelne Informationen anzeigen, indem man mit hide die ungewünschten ausblendet. Dabei wird aber immer der Titel des Projekts und die Finanzierung in Klammern angezeigt. 
Schön wäre es, wenn man nur den Inhalt des gewünschten Arrays/Variable zB der Publikationen anzeigen könnte, so dass man das direkt in die Seite einbauen kann und die Seite drumherum "bauen" kann.

**Comment by cassandre** [comment]
Ist im nächsten Update drin.

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/fau-cris/commit/4cee0702ad2ae90f316e4ed8f5cbd8e7185f221a umgesetzt.
