### ISSUE TITLE
Verknüpfung mehrerer Filter 

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/fau-cris#65]
Ich würde gerne mehrere Filter auf einmal in einen shortcode packen, also z.B.:
[cris orgID="123456" show="publications" type="buecher, zeitschriftenartikel"]

Wenn ich das mache, werden allerdings ALLE Publikationen ausgegeben, also gar kein Filter angewendet.

**Comment by cassandre** [comment]
Ist im nächsten Update drin.

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/fau-cris/commit/2024de4223e5bcd00c25c7692f55ca724d86d57c umgesetzt.
