### ISSUE TITLE
Laufende Projekte 

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/fau-cris#66]
Mail B.M.: Mit niedriger Prio: Für Projekte brauchen wir eine Möglichkeit, im Jahr X laufende Projekte auszugeben, also Projektstart <= Jahr X und Virtualenddate >= Jahr X

**Comment by FlorianFiller** [comment]
Würde gerne die Prio erhöhen und das seitens der PhilFak unterstützen:
Für unsere Fakultätsseite ist es nur sinnvoll, die (aktuell) **laufenden** Projekte anzeigen zu lassen und nicht nur die in dem jeweiligen Jahr gestarteten.

**Comment by cassandre** [comment]
Ich schau mal, was sich machen lässt. Kling ja nicht allzu kompliziert.

**Comment by FlorianFiller** [comment]
Vielen Dank!

Wie bekomme ich das nun über den shortcode angezeigt? 
Meine spekulativen Versuche mit year="current" oder current="1" etc. funktionieren leider nicht.

**Comment by cassandre** [comment]
current="1" ist der richtige Parameter. Ich habe es eben in der Dokumentation ergänzt, danke für den Hinweis. 
Funktioniert auch, ich habe es gerade auf http://www.test.rrze.uni-erlangen.de:2175/cris/cris-projekte/ noch mal getestet (oben mit current="1", weiter unten alle Projekte der PhilFak).

**Comment by FlorianFiller** [comment]
Danke!
