### ISSUE TITLE
Forschungsaktivitäten

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/fau-cris#67]
Der (in der Doku angegebene) shortcode

[cris show="activities"]

funktioniert wohl nicht. Zumindest führt er bei mir nur dazu, dass die Seite weiß bleibt (und - interessanterweise - der schwarze Word-Press-Balken am Kopf der Seite verschwindet).
Sh. Screenshot:
![cris_aktivitaten](https://cloud.githubusercontent.com/assets/12810141/22690177/bdd0551c-ed34-11e6-808f-4fb1945e2f03.png)

**Comment by cassandre** [comment]
Diesen Fehler konnte ich leider nicht reproduzieren. Ist er noch aktuell?

**Comment by FlorianFiller** [comment]
Ja - ist noch aktuell - bei mir entsteht durch den oben erwähnten shortcode immer noch eine leere Seite, in der die WordPress-Bedienleiste verschwindet.

**Comment by cassandre** [comment]
Fehler gefunden und gefixt, ist im nächsten Update drin.

**Comment by cassandre** [comment]
Gefixt in https://github.com/RRZE-Webteam/fau-cris/pull/79
