### ISSUE TITLE
Unterschiedliche Darstellung in Liste und Einzelansicht bei Publikation ODER In der Liste sollen URL und DOI auch zusammen möglich sein.

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#68]
In der Einzelansicht enthält die Standarddarstellung DOI und URL (sofern vorhanden): `[cris show="publications" publication=1026245]`

In der Liste wird die DOI nicht angezeigt, wenn eine URL vorhanden ist: `[cris show="publications" persid=172180]`

Frage: Gibt es einen Schalter, der die DOI auch in der Liste immer mit ausgibt?

**Comment by cassandre** [comment]
Eigentlich sollte die immer angezeigt werden. Wird sie bei mir auch. Kann sein, dass das mit dem nächsten Update erledigt ist. In der aktuellen dev-Version kann ich den Fehler jedenfalls nicht reproduzieren.

**Comment by cassandre** [comment]
Die DOI wird aktuell auch in (Standard-)Listen immer mit ausgegeben. Ich baue in den Einstellungen noch einen Schalter für die MLA-/APA-Ausgabe ein (analog zu den BibTex- und URL-Links). Dort wird sie momentan nicht angezeigt, ist aber vielleicht auch sinnvoll.
