### ISSUE TITLE
Darstellungsfehler (bug)

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/fau-cris#70]
Der Shortcode liefert an einer Stelle - mir ist völlig unklar, warum - zu zwei Publikationen nur den BibTex-Download und nicht die anderen Informationen. Auch nach dem Aktualisieren bleibt der Fehler auf beiden Seiten (deutsch und englisch) bestehen.
Shortcode: [cris orgID="141638" show="publications" type="zeitschriftenartikel" year="2017"]
Fehler siehe Bild (Vergleich CRIS - Homepage):
![bug_cris](https://cloud.githubusercontent.com/assets/12810141/23394314/ac4a27d2-fd88-11e6-90db-1c5a2501d783.png)

**Comment by m-w** [comment]
Wenn die Publikationen "ganz frisch" sind, dann könnte es sich um ein Cache-Problem handeln. Der CRIS-Cache wird jeweils um 7, 9, 13, 17 und 21 Uhr aktualisiert. Wenn das zutrifft, dann sollte die Darstellung ab ca. 9:20 Uhr passen.

Ein lokaler Cache könnte das noch etwas verzögern.

**Comment by cassandre** [comment]
Der Fehler kommt aus CRIS: Beim Publikationstyp "Journal Article" wird Article bei diesen beiden Publikationen klein geschrieben (vielleicht bei allen neueren?) und fällt dadurch durch einen bestimmten Filter, der die Darstellung auf der Seite regelt. 
Ich werde mit dem CRIS-Team absprechen, ob sie das fixen, oder ob ich die Inkonsistenz im Plugin auffangen soll.

**Comment by cassandre** [comment]
Ich habe den Fehler jetzt erst mal im Plugin abgefangen, das gleich installiert wird (https://github.com/RRZE-Webteam/fau-cris/commit/f2e01190fbfe25b1cd2b921e57b9f3d82c9e8545). Ich lasse den Issue aber mal offen zur finalen Klärung mit dem CRIS-Team).

**Comment by FlorianFiller** [comment]
Vielen Dank!

**Comment by m-w** [comment]
Ich kann auf Anhieb keine Publikation finden, wo "article" groß geschrieben wird. Sei's drum: Bitte die Vergleiche immer case-insensitive durchführen.
