### ISSUE TITLE
Falscher Export von Potenzen

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#75]
Aus dem CRIS werden Potenzen falsch an das CMS weitergeben.
Aus 10 hoch 7 im CRIS in der Beschreibung und dem Abstract wird 107 auf der Webseite.
Siehe 
https://cris.fau.de/converis/publicweb/Project/100888?share=false&cntpers=false&reqstfulltxt=false&reports=false&lang=1

**Comment by cassandre** [comment]
Die meisten HTML-Tags werden aus der Beschreibung herausgefiltert. Für <sup> und <sub> habe ich jetzt Ausnahmen hinzugefügt. 
Danke für den Hinweis, ist im nächsten Update drin (ca. Ende nächster Woche).

**Comment by anbininf12** [comment]
Die Potenzen werden leider noch mit ^ angezeigt:

Zukünftige Exascale-Systeme mit 10^7 Recheneinheiten und einer
Spitzenleistung von bis zu 10^18 FLOPS werden ein enges Codesign von

**Comment by cassandre** [comment]
Gefixt in https://github.com/RRZE-Webteam/fau-cris/pull/79

**Comment by anbininf12** [comment]
Änderungen der class_projekte.php wurde nicht in den Master übernommen.

Zeile 277

**Comment by cassandre** [comment]
War in der normalen Single-Ansicht drin, aber nicht in der Custom Single. Sollte jetzt passen. Sorry!
