### ISSUE TITLE
cris-custom zeigt keine Bilder

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#76]
Die Option #image# des cris-custom-Shorttags zeigt ein in CRIS vorhandenes Bild nicht an.

**Comment by cassandre** [comment]
Der Shorttag muss #image1#, #image2# etc. heißen.
Da in CRIS jeweils mehrere Bilder bei Forschung, Forschungsbereichen und Projekten hinterlegt werden können, muss die Nummer des Bildes mit angegeben werden.
