### ISSUE TITLE
Publikationen zum Forschungsbereich: "dual-use"

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#82]
Eigentlich sollten beim Forschungsbereich nur herausragende Publikationen verknüpft werden. Alle weiteren Publikationen sind dann über die Projekte zugänglich.

Allerdings gibt es Fälle, bei denen eine Vielzahl von Publikationen direkt dem Forschungsbereich zugeordnet werden - ohne verknüpftes Projekt.

Um beide Anforderungen bedienen zu können:

1. Limitierung der Anzeige "Publikationen zum Forschungsbereich" per konfigurierbarem Parameter (Top N Stück mit N = 5 als Standard). 
1. Ausgabe aller verknüpften Publikationen in anti-chronologischer Sortierung. Hier sollte man auf die/alle bestehenden Funktionen der Publikationsausgabe bei Orgas zurückgreifen.

**Comment by cassandre** [comment]
Zu 2.: Bis jetzt ist es so, dass, wenn die Anzahl der Publikationen begrenzt wird (items="3"), eine Listenansicht ausgegeben wird, also ohne Untergliederung nach Jahr oder Typ. 
Bedeutet "alle bestehenden Funktionen", dass nun auch diese Gliederung bei begrenzen Listen möglich sein soll? (wäre eher aufwändig) Oder nur sind nur die sonstigen Funktionen gemeint: Filter, Quotation und Sortierung nach created oder updated? 

Bei allen in diesem Issue angesprochenen Parameter würde ich es so machen, dass man die Parameter webseitenweit in den Einstellungen setzen kann. Man kann diese Einstellungen aber im Shortcode überschreiben.

**Comment by m-w** [comment]
Dier Beschränkung sollte am besten standardmäßig greifen. Wenn man wirklich alles haben will, dann bitte explizit. Hier steigt wahrscheinlich kurzfristig der Supportaufwand, aber nur so bekommen wir die Leute zur Zuordnung der wichtigen Publikationen.

Bei den Funktionen sollten wir Ticket #91 gleich mit berücksichtigen. Das ist dann praktisch das gleiche. Wahrscheinlich setzen wir uns für ein Refactoring besser mal zusammen?

Globale Schalter und überschreiben im Shortcode: Ja, gerne.

**Comment by m-w** [comment]
Schalter wird das Attribut `orderby`: Ist es gesetzt, so wird `items` ignoriert.

**Comment by cassandre** [comment]
Funktioniert: [cris show="fields" field="139" publications_start="2009" publications_orderby="type" items="3"] filtert und gliedert wie angegeben. Die Gliederung überschreibt die items-Angabe (s. https://github.com/RRZE-Webteam/fau-cris/issues/82#issuecomment-320610592).

**Comment by m-w** [comment]
Die Änderung bei der Beschränkung funktioniert nicht (mehr): `[cris show=fields field=139 publications_start=2009 items=3]` liefert den Standard von fünf Publikationen.

**Comment by cassandre** [comment]
Mein Fehler: Der Parameter muss publications_items heißen. [cris show="fields" field="139" publications_items="3"] funktioniert. Ich habe den Parameter geändert, damit er konsistent bleibt: Items bezieht sich auf das Hauptelement, publications_items auf die Publikationen, und ggf. könnte man auf diese Weise noch projects_items erweitern, ohne in Konflikt zu kommen.

Man könnte sich nur überlegen, ob es eine aussagekräftigere Bezeichnung als Items gibt. Aber die hat sich wahrscheinlich schon so eingebürgert.

**Comment by m-w** [comment]
D.h. wenn jemand jetzt bereits `items` verwendet, um mehr anzuzeigen, muss er/sie den Shortcode in jedem Fall anpassen... Wahrscheinlich ist jetzt die letzte Gelegenheit, den Namen anzupassen: `publication_limit`?

**Comment by cassandre** [comment]
Klingt gut. Ich würde nur publications im Plural lassen: publications_limit, publications_orderby,...
Man kann das ganze auch abwärtskompatibel gestalten und Items dann irgendwann später rausschmeißen.

**Comment by m-w** [comment]
Plural ist ok. Wenn `items` alleine hier keine Bedeutung mehr hat, dann kann es gleich raus, oder?

**Comment by cassandre** [comment]
Grundsätzlich sollte es bleiben (bzw. in Zukunft als "limit"), um Listen zu begrenzen. Bei allen anderen Forschungsleistungen (Publikationen, Auszeichnungen etc.) ist es vorhanden. Vielleicht will ja mal jemand eine Liste der Forschungsbereiche begrenzen. Ist zwar nicht sehr wahrscheinlich, aber der Einheitlichkeit halber würde ich es als Option drin lassen.

**Comment by m-w** [comment]
Klar, die Beschränkung brauchen wir praktisch überall. Gibt es die Option `items` derzeit noch anderswo im praktischen Einsatz?

**Comment by cassandre** [comment]
Ich weiß es nicht. Aber falls es noch jemand verwendet, habe ich es abwärtskompatibel geändert: Items funktioniert noch, wird aber von limit überschrieben.

**Comment by m-w** [comment]
Mergen!

**Comment by m-w** [comment]
Bevor wir das mergen, muss ich mindestens noch einem Lehrstuhl Bescheid geben. Gibt es eine Option, das zentrale CMS nach "items" zu durchsuchen?

**Comment by m-w** [comment]
Die "custom"-Ausgabe scheint nicht zu funktionieren, z.B. liefert dieser Schnipsel "nichts":

`[cris-custom show=fields field=39]
#publications#
[/cris-custom]`

**Comment by m-w** [comment]
Es scheint nicht die richtige ID der Forschungsbereiche genutzt zu werden. In den Logfiles hier taucht die "0" als ID auf.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/8939fb5e6f72e39654d81e6120e32854a83438b4.
