### ISSUE TITLE
Ausgabe Subtyp bei Abschlussarbeiten

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#83]
Im CMS wird der Untertyp einer Abschlussarbeit Dissertation nicht angezeigt auch wenn er eingetragen ist.

**Comment by m-w** [comment]
In den Zitationsstilen wird der Typ angegeben, sofern dies im Stil definiert ist. In der allgemeinen Ansicht dennoch sinnvoll.
