### ISSUE TITLE
Liste von Projekten, an denen einen Person beteiligt ist

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#84]
Ist es möglich beim CMS auszugeben, an welchen Projekten die Person X mit der CRIS-ID Y beteiligt ist?

**Comment by m-w** [comment]
Bei den Projekten kann die `persID` als Attribut angegeben werden, die Auswahl der Beteiligung erfolgt dann über `role=leader` bzw. `role=member` - beides in einer Liste halten wir für nicht besonders sinnvoll.

Damit man bei den Personen nicht immer prüfen muss, welche(n) Code(s) man einfügen muss, wäre die Ausgabe einer gegliederten Liste sinnvoll.

Also wenn beides vorhanden ist, ergibt `[cris show=projects persid=Y role=all]`
### Projektleitung
- Project 1
### Projektmitarbeit
- Project 2
- Project 3

Wenn nur ein Rollentyp vorhanden ist, ergibt `[cris show=projects persid=Z role=all]`
### Projektmitarbeit
- Project 2

Kommt das der Anforderung nahe?

**Comment by mduven** [comment]
Eine solche Ausgabe wäre bei uns ebenfalls sinnvoll. D.h. eine "gemischte" Ausgabe ist im moment noch nicht möglich, oder?

Eine andere Frage noch bezüglich der Projekte: Ist es möglich, nur laufende Projekte anzuzeigen?

**Comment by m-w** [comment]
#66 :-)

**Comment by cassandre** [comment]
`persid=Z` gibt jetzt alle Projekte einer Person aus (funktionierte bisher nur getrennt nach Rolle)
Mit `role=[leader|member]` kann man entsprechend filtern. 
`orderby=role` erzeugt eine Gliederung nach Projektleitung / Projektmitarbeit.
