### ISSUE TITLE
Person mit Vornamen >1 

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#85]
![link_autor](https://cloud.githubusercontent.com/assets/20298307/25698905/22c83f82-30c1-11e7-98d0-b2b60da3b957.png)
Hat eine Person mehrere Vornamen (Tanase, Alexandru-Petru), wird bei der Ausgabe der Publikationen im CMS kein Link beim Autor erzeugt, wenn in den Einstellungen des Plugins der Autoren-Link nicht ins CRIS sondern auf die CMS-Kontakt-Seite zeigen soll.
Der Benutzer ist auch ein Benutzer im CMS und hat eine gültige Kantakt-Seite.

**Comment by m-w** [comment]
Kann man das ggfs. im FAU-Person-Plugin korrigieren?

**Comment by anbininf12** [comment]
Der Fehler liegt im Zusammenspiel von class_tools.php mit dem xml-Feld relAuthors vom CRIS-Output.
Hier kommt Tanase AP zurück; class_tools.php sucht dann nach AP%Tanase in der CMS-DB, die Seite heißt aber Alexandru Tanase im CMS (oder Alexandru-Petru Tanase). 
Funktionen: public static function get_person_link, public static function person_exists
evtl. an anderer Stelle auch noch.
Wenn ich den Wordpress-Kontakt in AP Tanase umbenenne, dann funktioniert der Link. 

Besser wäre vielleicht statt relAuthors exportAuthors zu nehmen und ggf die Vornamen zu exploden.
Oder im Kontakt die CRIS-ID(s) hinterlegen und das entsprechende xml-Feld zu verwenden.

**Comment by Velines** [comment]
Um den Schwierigkeitslevel etwas zu erhöhen hier noch weitere interessante Fälle ;)
Mehrere Nachnamen, nur einer genutzt: https://cs12.cms.rrze.uni-erlangen.de/person/jorge-echavarria/
Vornamen mit Sonderzeichen: https://cs12.cms.rrze.uni-erlangen.de/person/ericles-sousa/ (hier der Vorname mit É, im CRIS nur E)
Zweiter Vorname ist Rufname: https://cs12.cms.rrze.uni-erlangen.de/person/akif-oezkan/ (nur Akif wird genutzt)

**Comment by m-w** [comment]
Für diese Punkte existieren Lösungen:

1. Genutzter Nachname weicht ab: http://blogs.fau.de/cris/docs/how-to/zusaetzliche-visitenkarte-anlegen/ (den Umzug der Visitenkarte auf Publikationen, etc. kann dann cris-support@fau.de erledigen).
1. Fehlende Sonderzeichen: Bitte direkt in der Personalabteilung Bescheid geben, damit dies korrigiert wird.
1. Abweichender Rufname: https://blogs.fau.de/cris/docs/how-to/rufnamen-festlegen/
