### ISSUE TITLE
Unvollständiges Mapping futurePublicationType bei Preprints

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#86]
Während mit dem Shortcode `[cris publication="1063742"]` keine Ausgabe erfolgt, funktioniert `[cris publication="1063742" quotation="apa"]` (dito MLA).

**Comment by anbininf12** [comment]
Hallo,

für das Element futurePublicationType gibt es im Plugin keine Behandlung
für den Wert Edited Volume.
Wenn man die Publikation auf Book setzt (Behandlung vorhanden). dann
wird die Pub angezeigt.
Ich setze die Pub jetzt mal auf Book.

**Comment by cassandre** [comment]
Fixed in https://github.com/RRZE-Webteam/fau-cris/commit/918896988d42fe9464156248a90083716b7ed5ef
