### ISSUE TITLE
Doppelte Anzeige Personen zum Forschungsbereich bei verschiedenen Rollen

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#87]
Ist eine Person Projektleiter und auf einem weiteren Projekt als Projektmitarbeiter geführt, so wird die Person doppelt beim Forschungsbereich gelistet. Bsp ist der FB 44.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/520492070c5892eeac395b5b55b48f0e8c30ed4c
