### ISSUE TITLE
Interne Seite für Publikationen

### ISSUE THREAD

**Issue by fkranz** [RRZE-Webteam/fau-cris#88]
Schön wäre es, wenn der Titel in der Publikationsliste nicht auf das CRIS sondern auf
eine interne Seite verlinken (so wie das jetzt bei den
Lehrveranstaltungen mit der univis-Plugin geht).
Diese Seite könnte im einfachsten Fall zB so aussehen:
https://lgdv.cms.rrze.uni-erlangen.de/publikationen/gropbs-fast-solver-for-implicit-electrostatics-of-biomolecules/

Im normalen Textfeld steht der Abstract, den man ja aus dem CRIS
entnehmen kann und in der oberen Sidebar die Informationen die man über
[cris publication=id] erhält.

Optimalerweise würde diese Seite automatisch erstellt (zB als Kind von
Publikationen, benannt nach dem Titel oder der ID, wie die automatische Integration von Forschungsprojekten) und wäre dann
anpassbar, sodass man noch zusätzliche Informationen wie zB ein Video im
Hautpfeld und eine Download-Section in der Sidebare einzufügen kann:
https://lgdv.cms.rrze.uni-erlangen.de/publikationen/interactive-painting-and-lighting-in-dynamic-multi-projection-mapping/

Am benutzerfreundlichsten wäre dann wieder, wenn man diese Dinge (zB ein
zusätzliches Video oder mehr Text, einen Preprint der Papers oder
zusätzliche Dateien wie Code) direkt im CRIS eintragen könnte, dazu müsste aber wohl auch das CRIS angepasst werden.

**Comment by m-w** [comment]
Können Sie bitte eine Einschätzung darüber geben, wie viele Publikationen bei Ihnen so "reichhaltig" sind?

**Comment by fkranz** [comment]
Also ich hab jetzt für mal 2016 auf unsere aktuellen Seite geschaut, da sind es etwa 50% der Publikationen. 
Besonders Videos sind bei uns eben oft Teil der Publikation.

**Comment by m-w** [comment]
Derartige Supplementals können Sie in CRIS direkt nicht ablegen, dazu fehlen dem System einfach die passenden Features.

Was halten Sie von folgendem Vorschlag:

1. Die "Supplemental-Seite" wird als URL der Publikation in CRIS hinterlegt (geht jetzt schon).
1. In das WordPress-Plugin wird ein Schalter eingebaut, welcher zwischen der Verlinkung auf das Forschungsportal und der hinterlegten URL unterscheidet.

Mit Blick auf in Zukunft verwaiste URLs sollten wir ein wenig aufpassen, dass die Pflege der URLs sichergestellt wird. Daher wird die Standardeinstellung immer die Verlinkung zum Forschungsportal sein.

Für die Realisierung von Punkt 2 kann ich Ihnen allerdings noch keinen Zeitrahmen nennen. Wenn Sie grundsätzlich dem Vorschlag zustimmen, können Sie die Daten schon jetzt entsprechend vorbereiten.

**Comment by m-w** [comment]
Nachtrag: Die automatische Erstellung der Seite für die Zusatzinhalte würde ich nicht anstreben.

Zu prüfen ist weiterhin, ob Sie auf dieser Seite mit dem Shortcode [cris-custom](https://www.wordpress.rrze.fau.de/plugins/fau-cris/erweiterte-optionen/) sich die passenden Inhalte an beliebige Positionen holen können.

**Comment by fkranz** [comment]
Erstmal Danke für das schnelle Feedback!

Zunächst mal zu cris-custom: Soweit ich das sehe, kann ich das im Grunde nur für Forschungsbereiche und Projekte anwenden, ich wüsste also nicht wie mir das weiter helfen würde.

Gibt es denn eine Möglichkeit, zumindest den Abstract zu einer Publikation aus dem cris abzufragen (dafür ist ja schließlich bereits ein Feld vorhanden)?

Zu 1.:
Ja, das war genau der Weg, den wir uns alternativ auch schon überlegt hatten, das gibt nur dann ein Problem, wenn die Arbeit zB lehrstuhlübergreifend entstanden ist und jeder Lehrstuhl das gerne auf seine eigene Seite verlinkt hätte.

Zu 2.:
Das würde uns auf jeden Fall schon sehr entgegenkommen.

Das händische anlegen sorgt halt wieder dafür das Daten an verschiedenen Orten gepflegt werden müssen, was ja eigentlich eher vermieden werden sollte.

**Comment by fkranz** [comment]
Da wir gerne spätestens Ende des Jahres auf unsere neue Webseite umstellen möchten, wollte ich nachfragen, ob es schon eine Idee gibt, wann unsere Anforderungen möglich sein könnten?

Ich hab mir auch den Code nochmal ein bisschen angesehen und sehe folgende (einfache?) Möglichkeit:
Man könnte an der Stelle wo der Link ins CRIS für die Überschrift erstellt wird überprüfen ob eine durch die CRIS-ID der Publikation definierte (zB /publikationen/123456-details oder sowas Ähnliches) lokale Seite existiert und dann auf diese Verlinken oder eben ins CRIS, wenn sie nicht existiert.

Das würde für Nutzer, die keine lokalen Seiten für Publikationen anlegen wollen, keine zusätzliche Arbeiten verursachen und für die, die es nutzen wollen, aber den entscheidenden Vorteil bringen, dass man es für einzelne Publikationen machen kann und die Seite problemlos nach der Veröffentlichung im CRIS anlegen kann.

**Comment by fkranz** [comment]
Ich habe gerade auch gesehen, dass im Grunde genau das, was wir für Publikationen gerne hätten für Forschungsprojekte bereits funktioniert.

Dort verlinkt "Mehr Informationen" entweder auf eine Interne Seite mit dem exakten Titel des Projekts oder aber aufs CRIS, wenn eine solche Seite nicht exisitert.

Das wäre perfekt.

**Comment by m-w** [comment]
Eine solche Lösung können wir einfügen.

**Comment by cassandre** [comment]
Ich habe mal einen Rundumschlag daraus gemacht: Bei **allen** verlinkten Objekten wird jetzt zuerst geschaut, ob es dazu eine Seite im eigenen Webauftritt gibt (=Titel identisch), ansonsten der Link zu cris.fau.de gesetzt.

Im eigenen Webauftritt wird erst nach Unterseiten unterhalb der betroffenen Seite geschaut, danach erst im gesamten Webauftritt. Oft hat man ja z.B. eine Publikationsliste und darunter die Detailseiten zu den einzelnen Publikationen.
