### ISSUE TITLE
Darstelllung der Auszeichnungen fehlerhaft

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-cris#89]
Wenn einer Auszeichnung mehrere Personen zugeordnet sind (z.B. Best Paper Award), dann werden diese falsch angezeigt. 
In der Funktion make_list () wird in Zeile 236/237 nur der erste und der letzte Eintrag des Autoren-Arrays betrachtet. Sind aber mehrere Autoren zugeordnet, wird der Nachname des des ersten Autoren als Vorname und der Vorname des letzten Autoren als Nachname verwendet.

![award_fehler1](https://cloud.githubusercontent.com/assets/20298307/25995641/9a2f40a4-3713-11e7-8968-9c59058ddf6a.png)
![award_fehler2](https://cloud.githubusercontent.com/assets/20298307/25995640/9a2d5b72-3713-11e7-9725-b0119e11b6cb.png)

**Comment by cassandre** [comment]
Fixed in https://github.com/RRZE-Webteam/fau-cris/commit/ca8eccc76c7628e4114d55afb078efa87d5883de
