### ISSUE TITLE
Filter auf "FAU-Publikationen"

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#90]
Analog #78 (reicht im Gegensatz dazu für Organisationen)

Hintergrund: viele Autoren nutzen die aktuelle Visitenkarte des Lehrstuhls für Arbeiten, welche nicht an der FAU entstanden sind (Alternative siehe [hier](http://blogs.fau.de/cris/docs/how-to/zusaetzliche-visitenkarte-anlegen/)). Auf Lehrstuhllisten sollen diese herausgefiltert werden.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/98167b0dbfd6972f3057e795863a664164eb0fae.
fau=1 -> nur FAU-Publikationen
fau=0 -> nur nicht-FAU-Publikationen
keine Angabe -> kein Filter

**Comment by m-w** [comment]
Wer dokumentiert das auf https://www.wordpress.rrze.fau.de/plugins/fau-cris/ ?

**Comment by cassandre** [comment]
War schon: unter Filter, zweitletzter Punkt. Ich habe es jetzt mal höher gesetzt, direkt unter die Publikations-ID
