### ISSUE TITLE
Anzeige "srcauthors" bei älteren Publikationen und unvollständiger Verknüpfung

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#92]
Wenn eine Publikation nicht vollständig verknüpft ist (möglich bei "älter als 5 Jahre"), so sollten nicht die verknüpften Autoren, sondern der srcauthors-String für die Ausgabe genutzt werden. Eine Unterscheidung ist über das Attribut "complete author relations" möglich.

Hier sind dann natürlich keine Verlinkungen möglich. Und es kann ziemlicher Müll im String vorkommen...

**Comment by m-w** [comment]
Nicht an der FAU entstandene Publikationen können ebenfalls unvollständig verknüpft sein. Bei der Abfrage auf "complete author relations" ändert sich aber nichts.

**Comment by cassandre** [comment]
Sieht zwar etwas seltsam aus, wenn zwischendurch Autoren mit komplettem Vornamen auftauchen, aber wenn das so gewollt ist... Sollte jetzt funktionieren.

**Comment by m-w** [comment]
Wenn die vollständige Verknüpfung nicht durchgeführt wurde, haben wir nur die Wahl zwischen "fehlenden Autoren" und "komischer Darstellung". Bei Fakultätsseiten kann das u.U. seltsam aussehen.
