### ISSUE TITLE
Auszeichungen: Filterung auf "andere"

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#94]
Der Shortcode `[cris show=awards orgid=142351 type=andere]` sollte zwei Preise finden, liefert aber keine. Ohne die Type-Einschränkung werden die entsprechenden Preise angezeigt.

**Comment by cassandre** [comment]
"andere" liefert den Typ "Kleine Preise". Ist das korrekt? Wenn ja, gefixt in https://github.com/RRZE-Webteam/fau-cris/commit/f8ffff5778c3bb83cc6e0e6a05c06b8392e33fc9

**Comment by m-w** [comment]
Bitte die Option auf "weitere" ändern und unter https://www.wordpress.rrze.fau.de/plugins/fau-cris/ dokumentieren (da fehlen die Optionen für Preise).

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/0d276992c6b76d737bea31e07cb7b9c19807297f
