### ISSUE TITLE
Sortierung der Preise

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-cris#95]
Die Sortierung der Preise erfolgt offenbar nach Vornamen sortiert: https://www.tf.fau.de/forschung/auszeichnungen/

**Comment by cassandre** [comment]
Um nach Nachnamen zu sortieren, bräuchte ich eine eindeutige Kennzeichnung des Nachnamens, z.B. durch einen Trenner zwischen Vor- und Nachnamen. Z.B. wie bei den Patenten (exportInventors) mit Doppelpunkt.
Das würde auch für #89 eine zuverlässigere Lösung schaffen.

**Comment by m-w** [comment]
Neues Attribut "exportNames" ist jetzt vorhanden. Vollständige Füllung ist erst morgen fertig, zum Testen kann man ID 631 nutzen.

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/fau-cris/commit/3873bec66c267ef35f93bc34af5820973cfa2cb3
